# 1. RAG 평가 개요
- RAG 평가란 RAG 시스템이 주어진 입력에 대해 얼마나 효과적으로 관련 정보를 검색하고, 이를 기반으로 정확하고 유의미한 응답을 생성하는지를 측정하는 과정이다. 
- **평가 요소**
    - **검색 단계 평가**
        - 입력 질문에 대해 검색된 문서나 정보의 관련성과 정확성을 평가.
    - **생성 단계 평가**
        - 검색된 정보를 기반으로 생성된 응답의 품질, 정확성등을 평가.
- **평가 방법**
    - **온/오프라인 평가**
        1. **오프라인 평가**
            - 미리 준비된 데이터셋을 활용하여 RAG 시스템의 성능을 측정한다.
        2. **온라인 평가**
            - 실제 사용자 트래픽과 피드백을 기반으로 시스템의 실시간 성능을 평가한다.
    - **정량적/정성적 평가**
        1. 정량적 평가
            - 자동화된 지표를 사용하여 생성된 텍스트의 품질을 평가한다.
        2. 정성적 평가
            - 전문가나 일반 사용자가 직접 생성된 응답의 품질을 평가하여 주관적인 지표를 평가한다.

# 2. [RAGAS](https://www.ragas.io/)
- RAGAS는 RAG 파이프라인을 **정량적으로 평가하는** 오픈소스 프레임 워크이다. 
- RAGAS 문서: https://docs.ragas.io/en/stable/
## 2.1 설치
- `pip install ragas rapidfuzz`

## 2.2 RAGAS 평가 지표 개요
![ragas_score](figures/ragas_score.png)
- **Generation**
    - llm 모델이 생성한 답변에 대한 평가 지표들.
    - **Faithfulness(신뢰성)**
        -  생성된 답변과 검색된 문서(context)간의 관련성을 평가하는 지표
        -  생성된 답변이 주어진 문맥(context)에 얼마나 충실한지를 평가하는 지표로 할루시네이션에 대한 평가로 볼 수있다.
    - **Answer relevancy(답변 적합성)**
        - 생성된 답변과 사용자의 질문간의 관련성을 평가하는 지표
        - 생성된 답변이 사용자의 질문과 얼마나 관련성이 있는지를 평가하는 지표.
- **Retrieval**
    -  질문에 대해 검색한 문서(context)들에 대한 평가
    -  **Context Precision(문맥 정밀도)**
        -  검색된 문서(context)들 중 질문과 관련 있는 것들이 **얼마나 상위 순위에 위치하는지** 평가하는 지표.
    -  **Context Recall(문맥 재현률)**
        -  검색된 문서(context)가 정답(ground-truth)의 정보를 얼마나 포함하고 있는지 평가하는 지표.
- 이러한 지표들은 RAG 파이프라인의 성능을 다각도로 평가하는 데 활용된다.
![RAGAS_score2](figures/RAGAS_score2.png)

## 2.3 주요 평가지표
### 2.3.1 Generation 평가
- LLM이 생성한 답변에 대한 평가
  
#### 2.3.1.1 Faithfulness (신뢰성)
- 생성된 답변이 얼마나 주어진 검색 문서들(context)를 잘 반영해서 생성되었는지 평가한다. 할루시네이션에 대한 평가라고 할 수 있다. 
- 점수범위: **0 ~ 1** (1에 가까울수록 좋음)
- 답변에 포함된 모든 주장이 context에서 얼마나 추출 가능한지를 확인한다.

##### 2.3.1.1.1평가 방법
1. Answer에서 주장 구문(claim statement)들을 생성(추출)한다. (주장이란, 질문(user input)과 관련된 내용)
    - 예) 
        - **질문**: 한국의 수도는 어디이고 인구는 얼마나 되나요? 
        - **LLM 답변**: 한국의 수도는 서울이고 인구수는 3000만명이다. 
        - **주장(claim)**: 
            1. 한국의 수도는 서울이다.
            2. 인구수는 3000만명이다.
2. 각 주장들을 context로 부터 추론 가능한지 판단한다. 이를 바탕으로 faithfulness 점수를 계산한다.
    - 예)
        - context: 한국은 동아시아에 위치하고 있는 나라다. 한국의 수도는 서울이다. .... 한국의 인구는 5000만명이고 서울에 1000만이 살고 있다.
        - 위 context에서 추론 가능한 주장: 
            - 한국의 수도는 서울이다. -> context에서 추론가능한 주장.
            - 한국의 인구는 3000만명이다. -> context에서 추론 불가능한 주장.
3. **Faithfulness score** 를 계산한다. 총 주장 수 중에서 context로 부터 추론가능한 주장의 개수.    
    - 예)
        - Faithfulness Score = $\cfrac{1}{2} = 0.5$ (두 개의 주장 중 한 개의 주장만 context에서 유추할 수있다.)
    - LLM 답변에서 주장을 추출 하는 것과 각 주장이 context에서 추론 가능한 지를 판단하는 것은 LLM 을 활용한다.
- 공식
    $$
    \text{Faithfulness Score}\;=\;\cfrac{\text{주어진\;context\;에서\;추론할\;수\;있는\;주장의\;개수}}{\text{총\;주장\;개수}}
    $$

### 2.3.2 Answer relevancy (답변 적합성)
- 생성된 답변이 질문(user input)에 얼마나 잘 부합하는 지를 평가한다.
- 점수 범위: -1~1 (1에 가까울수록 좋음)
- LLM이 생성한 답변을 기반으로 질문들을 생성한다. 이렇게 생성한 질문들과 실제 질문(user input) 간의 유사도를 측정한다.

#### 2.3.2.1 평가방법
1. LLM이 생성한 답변을 기반으로 질문들을 생성한다.
    - 예) 
        - **LLM** 답변: 한국의 수도는 서울이고 인구수는 3000만명이다. 
        - **생성된 질문**: 
            1. 한국의 수도는 어디이고 인구는 얼마나 되나요?
            2. 한국의 수도는 어디인가요?
            3. 한국의 인구는 얼마나 되나요?
2. 실제 질문과 생성한 질문간의 코사인 유사도를 측정한다. 그 평균이 최종 점수가 된다.
    - 예)
        - **실제 질문**: 한국의 수도는 어디이고 인구는 얼마나 되나요?
        - **생성된 질문**: 
            1. 한국의 수도는 어디이고 인구는 얼마나 되나요?
            2. 한국의 수도는 어디인가요?
            3. 한국의 인구는 얼마나 되나요?
- 공식
  $$
    \cfrac{1}{N} \sum_{i=1}^{N} \text{cosine\_similarity}(q_{\text{user}_{_i}}, q_{\text{generated}})
  $$

## 2.4 Retrieval 평가
Vector store에서 검색한 context에 대한 평가

### 2.4.1 Context Precision
- 검색된 문서(context)들 중 질문과 관련 있는 것들이 얼마나 **상위 순위**에 있는 지 평가.
- 점수 범위: 0~1 (1에 가까울수록 좋음)


#### 2.4.1.1평가방법

- 공식
$$
 \text{Context\;Precision@K} = \frac{\sum_{k=1}^{K} \left( \text{Precision@k} \times v_k \right)}{\ 상위\;K개\;결과에서의\;관련\;항목\;수}
$$
$$
 \text{Precision@k} = \frac{\text{True\;positive@k}}{(\text{True\;positive@k} + \text{False\;positive@k})} \\
$$
- $\text{Precision@k}$: 개별 문서에 대한 Precision
- K: context 의 개수(chuck 수)
- $v_k$: 관련성 여부로 0 또는 1. (0: 관련 없음, 1: 관련 있음)

#### 2.4.1.2 예시
- 질문과 context 관련성의 예
    - 질문: 한국의 수도는 어디이고 인구는 얼마나 되나요?
    - **높은 정밀도 context들**: 질문과 직접적인 관련이 있는 문서들
        - 한국의 수도는 서울이고 인구는 5000만명 입니다. 
        - 한국의 수도는 서울입니다.
        - 한국은 동아시아에 위치해 있는 국가로 수도는 서울입니다.
        - 한국의 인구는 5000만명 입니다.
    - **낮은 정밀도 context**: 한국과 관련있어 검색될 수 있지만 질문과 직접적 관련이 없다. 
        - 한국은 동아시아에 위치한 국가입니다.
        - 한국의 K-pop은 전 세계적으로 유명합니다.
        - 비빔밥, 불고기는 한국의 대표적인 음식입니다.
    - **높은 정밀도의 context이 상위 순위에 위치했으면 높은 점수를 받는다.**

- 점수 계산 예:
    - **상위 5개의 검색 결과 중 1번째, 3번째, 4번째 문서가 관련이 있다고 가정하자.**
    - **Precision@K 계산**
        ```bash
            Precision@1 = 1/1 = 1.0    # True positive@1/(True positive@1 + False positive@1).  1/1(1번 문서 계산 시에는 1개 문서만 있으므로 분모가 1이 된다.)
            Precision@2 = 1/2 = 0.5
            Precision@3 = 2/3 ≈ 0.67    
            Precision@4 = 3/4 = 0.75
            Precision@5 = 3/5 = 0.6
        ```
    - **vk의 값**
        - 1번째: $v_1 = 1$ - 관련있음
        - 2번째: $v_2 = 0$ - 관련없음
        - 3번째: $v_3 = 1$ - 관련있음
        - 4번째: $v_4 = 1$ - 관련있음
        - 5번째: $v_5 = 0$ - 관련없음

    - **Context Precision@5**
        $$
        \text{Context\;Precision@5} = \frac{(1.0 \times 1) + (0.5 \times 0) + (0.67 \times 1) + (0.75 \times 1) + (0.6 \times 0)}{3} = \frac{1.0 + 0 + 0.67 + 0.75 + 0}{3} ≈ 0.807
        $$

### 2.4.2 Context Recall (문맥 재현률)
- 검색된 문서(context)가 얼마나 정답(ground-truth)의 정보를 포함있는 지 평가하는 지표
- 점수 범위: 0~1 (1에 가까울수록 좋음)
- **정답(ground truth)의 각 주장(claim)이 검색된 context와 얼마나 일치**하는지 계산함.

#### 2.4.2.1 평가방법
1. 정답에서 주장(claim)들을 생성(추출)한다.
    - 예) 
        - **정답**: 한국의 수도는 서울이고 인구수는 5000만명이다. 
        - **주장(claim)**: 
            1. 한국의 수도는 서울이다.
            2. 인구수는 5000만명이다.
2. 각 주장(claim)의 정보를 검색된 contexts에서 찾을 수 있는지 판별한다. 이를 바탕으로 context recall 점수를 계산한다.
    - 예)
        - context: 한국은 동아시아에 위치하고 있는 나라다. 한국의 수도는 서울이다.
        - 위 context에서 추론 가능한 주장: 
            - 한국의 수도는 서울이다. -> context에서 찾을 수 있다.
            - 한국의 인구는 5000만명이다. -> context에서 찾을 수 없다.
3. **Context Recall Score** 를 계산한다. 총 주장 수 중에서 context로 부터 찾을 수 있는 주장의 개수.
    - 예)
        - Context Recall Score = $\cfrac{1}{2} = 0.5$ (두 개의 주장 중 한 개의 주장만 context에서 찾을 수 있다.)

- 공식
    $$
    \text{Context Recall Score}\;=\;\cfrac{\text{GT의\;주장\;중\;주어진\;context\;에서\;찾을\;수\;있는\;주장의\;개수}}{\text{GT의\;총\;주장\;개수}}
    $$

# 3. RAGAS 평가 실습

In [21]:
# !uv pip install ragas rapidfuzz
# 설치 후 커널 재시작

In [4]:
# docker run -p 6333:6333 -p 6334:6334   -v qdrant_storage:/qdrant/storage   qdrant/qdrant
# termianal에서 실행

In [5]:
from langchain_text_splitters import MarkdownHeaderTextSplitter
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.runnables import RunnablePassthrough
from langchain_core.output_parsers import StrOutputParser

from langchain_openai import ChatOpenAI
from langchain_qdrant import FastEmbedSparse, QdrantVectorStore, RetrievalMode
from qdrant_client import QdrantClient, models
from qdrant_client.models import Distance, SparseVectorParams, VectorParams
from langchain_openai import OpenAIEmbeddings

from dotenv import load_dotenv

load_dotenv()

True

## 0. 패키지 설치

In [12]:
# 필요한 library: pymupdf pdfplumber pillow openai qdrant-client langchain-core langchain-openai langchain-qdrant langchain-text-splitters python-dotenv

## 1. 설정 및 클라이언트 준비

In [13]:
import os
import re
import glob
import uuid
from pathlib import Path

import fitz  # PyMuPDF
import pdfplumber
from PIL import Image
from openai import OpenAI
from dotenv import load_dotenv

from qdrant_client import QdrantClient
from qdrant_client.models import Distance, VectorParams, Filter, FieldCondition, MatchValue

from langchain_core.documents import Document
from langchain_openai import OpenAIEmbeddings
from langchain_qdrant import QdrantVectorStore
from langchain_text_splitters import RecursiveCharacterTextSplitter

load_dotenv()

# ----- 설정값 -----
GUIDANCE_DIR = "./길라잡이"          # 이 폴더 안의 모든 PDF를 찾아서 적재

QDRANT_URL = os.getenv("QDRANT_URL", "http://localhost:6333")
QDRANT_API_KEY = os.getenv("QDRANT_API_KEY") or None
COLLECTION_NAME = "guidance_vectordb"

CHAT_MODEL = "gpt-5.4-mini"                          # 표 요약 / 이미지 캡션용
EMBED_MODEL = "text-embedding-3-large"         # large 임베딩 모델
EMBED_DIM = 3072

CHUNK_SIZE = 800       # 텍스트 청크 최대 글자 수 (splitter 기준)
CHUNK_OVERLAP = 150    # 청크 간 겹치는 글자 수 (문맥 끊김 방지)

openai_client = OpenAI()
qdrant_client = QdrantClient(url=QDRANT_URL, api_key=QDRANT_API_KEY)
embeddings = OpenAIEmbeddings(model=EMBED_MODEL)


def ensure_collection():
    existing = [c.name for c in qdrant_client.get_collections().collections]
    if COLLECTION_NAME in existing:
        print(f"'{COLLECTION_NAME}' collection이 이미 존재합니다.")
        return
    qdrant_client.create_collection(
        collection_name=COLLECTION_NAME,
        vectors_config=VectorParams(size=EMBED_DIM, distance=Distance.COSINE),
    )
    print(f"'{COLLECTION_NAME}' collection 생성 완료 (dim={EMBED_DIM})")


ensure_collection()

vectorstore = QdrantVectorStore(
    client=qdrant_client,
    collection_name=COLLECTION_NAME,
    embedding=embeddings,
)

pdf_paths = sorted(glob.glob(str(Path(GUIDANCE_DIR) / "*.pdf")))
print(f"'{GUIDANCE_DIR}' 안에서 발견된 PDF {len(pdf_paths)}개")
for p in pdf_paths:
    print(" -", p)

'guidance_vectordb' collection이 이미 존재합니다.
'./길라잡이' 안에서 발견된 PDF 2개
 - 길라잡이\사병_길라잡이.pdf
 - 길라잡이\초급간부_길라잡이.pdf


## 2. 텍스트 정제

In [14]:
def clean_text(text: str) -> str:
    # Private Use Area (U+E000–U+F8FF) 문자 제거
    text = re.sub(r'[\ue000-\uf8ff]', '', text)
    # 과도한 공백/빈 줄 정리
    text = re.sub(r'[ \t]+', ' ', text)
    text = re.sub(r'\n{3,}', '\n\n', text)
    return text.strip()


## 3. 표 추출 → 마크다운 → 요약

In [16]:
def table_to_markdown(table_rows):
    rows = [[cell if cell is not None else "" for cell in row] for row in table_rows]
    if not rows:
        return ""
    header = rows[0]
    body = rows[1:]
    md_lines = ["| " + " | ".join(header) + " |", "| " + " | ".join(["---"] * len(header)) + " |"]
    for row in body:
        md_lines.append("| " + " | ".join(row) + " |")
    return "\n".join(md_lines)


def extract_tables(pdf_path: str):
    tables_out = []
    with pdfplumber.open(pdf_path) as pdf:
        for page_num, page in enumerate(pdf.pages, start=1):
            for table in page.extract_tables():
                if not table or len(table) < 2:
                    continue
                md_table = table_to_markdown(table)
                tables_out.append({"page": page_num, "markdown": md_table})
    return tables_out


def summarize_table(table_markdown: str) -> str:
    response = openai_client.chat.completions.create(
        model=CHAT_MODEL,
        max_completion_tokens=300,
        messages=[{
            "role": "user",
            "content": (
                "다음은 문서에서 추출한 표입니다. 이 표가 어떤 내용을 담고 있는지 "
                "검색에 활용할 수 있도록 2~4문장의 한국어로 요약해줘. "
                "컬럼이 의미하는 바와 주요 수치/항목을 포함해줘.\n\n"
                f"{table_markdown}"
            ),
        }],
    )
    return response.choices[0].message.content.strip()


## 4. 텍스트 청킹 (페이지 단위)

이 PDF는 법령처럼 문장이 페이지를 넘어 쭉 이어지는 문서가 아니라, 페이지 하나하나가 그 자체로 하나의 토픽/안내 단위로 디자인된 문서입니다. 그래서 페이지 경계를 문맥 단위로 그대로 씁니다: **원칙적으로 한 페이지 = 한 청크**입니다.

In [17]:
text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=CHUNK_SIZE,
    chunk_overlap=CHUNK_OVERLAP,
    separators=["\n\n", "\n", ". ", " ", ""],
)

# 이 길이를 넘는 페이지만 splitter로 추가 분할 (그 외엔 페이지 통째로 한 청크)
PAGE_OVERFLOW_THRESHOLD = 1200


def chunk_text_by_page(pdf_path: str) -> list[dict]:
    """페이지 단위로 청크를 만든다. 페이지가 너무 길 때만 그 페이지 안에서 추가로 나눈다."""
    doc = fitz.open(pdf_path)
    results = []

    for page_num, page in enumerate(doc, start=1):
        page_text = clean_text(page.get_text("text"))

        if not page_text:
            continue  # 텍스트 없는 페이지(이미지만 있는 페이지 등)는 건너뜀

        if len(page_text) <= PAGE_OVERFLOW_THRESHOLD:
            results.append({"page": page_num, "text": page_text})
        else:
            # 이 페이지만 너무 길어서 임베딩이 흐려질 수 있는 경우 -> 페이지 내부에서만 분할
            sub_chunks = text_splitter.split_text(page_text)
            for sub in sub_chunks:
                results.append({"page": page_num, "text": sub})

    doc.close()
    return results


## 6. PDF 1개 → LangChain `Document` 리스트로 통합

In [18]:
ID_NAMESPACE = uuid.NAMESPACE_URL


def make_id(doc_name: str, chunk_type: str, index: int) -> str:
    """같은 PDF를 다시 적재해도 같은 ID가 나오도록 결정론적으로 생성 (재실행 시 upsert로 덮어씀)"""
    return str(uuid.uuid5(ID_NAMESPACE, f"{doc_name}::{chunk_type}::{index}"))


def build_documents_for_pdf(pdf_path: str) -> tuple[list[Document], list[str]]:
    doc_name = Path(pdf_path).name
    documents = []
    ids = []
    counter = 0

    # 1) 텍스트 청크
    text_chunks = chunk_text_by_page(pdf_path)
    for c in text_chunks:
        documents.append(Document(
            page_content=c["text"],
            metadata={"doc_name": doc_name, "page": c["page"], "type": "text"},
        ))
        ids.append(make_id(doc_name, "text", counter))
        counter += 1

    # 2) 표
    tables = extract_tables(pdf_path)
    for t in tables:
        summary = summarize_table(t["markdown"])
        documents.append(Document(
            page_content=summary,
            metadata={
                "doc_name": doc_name, "page": t["page"], "type": "table",
                "table_markdown": t["markdown"], "summary": summary,
            },
        ))
        ids.append(make_id(doc_name, "table", counter))
        counter += 1

    print(f"[{doc_name}] 텍스트 {len(text_chunks)} / 표 {len(tables)} → 총 {len(documents)}개")
    return documents, ids


## 7. 디렉토리 전체 적재 (upsert)

In [19]:

def upsert_documents(documents: list[Document], ids: list[str], batch_size: int = 100):
    for i in range(0, len(documents), batch_size):
        batch_docs = documents[i:i + batch_size]
        batch_ids = ids[i:i + batch_size]
        vectorstore.add_documents(documents=batch_docs, ids=batch_ids)
        print(f"  upsert 진행: {min(i + batch_size, len(documents))}/{len(documents)}")


def run_pipeline(directory: str = GUIDANCE_DIR):
    paths = sorted(glob.glob(str(Path(directory) / "*.pdf")))
    print(f"'{directory}'에서 PDF {len(paths)}개 발견, 적재 시작\n")

    total_chunks = 0
    for pdf_path in paths:
        documents, ids = build_documents_for_pdf(pdf_path)
        upsert_documents(documents, ids)
        total_chunks += len(documents)
        print()

    print(f"완료: PDF {len(paths)}개 / 총 {total_chunks}개 청크 적재")


# 실행
run_pipeline(GUIDANCE_DIR)

'./길라잡이'에서 PDF 2개 발견, 적재 시작

[사병_길라잡이.pdf] 텍스트 84 / 표 59 → 총 143개
  upsert 진행: 100/143
  upsert 진행: 143/143

[초급간부_길라잡이.pdf] 텍스트 92 / 표 102 → 총 194개
  upsert 진행: 100/194
  upsert 진행: 194/194

완료: PDF 2개 / 총 337개 청크 적재


## 8. 검색 예시
`vectorstore.similarity_search`로 기본 검색, `filter`로 `type`(text/table/image) 등 메타데이터 필터링도 가능합니다.

In [22]:
def search(query: str, k: int = 5, type_filter: str = None):
    qfilter = None
    if type_filter:
        qfilter = Filter(must=[FieldCondition(key="metadata.type", match=MatchValue(value=type_filter))])

    results = vectorstore.similarity_search_with_score(query, k=k, filter=qfilter)

    for doc, score in results:
        print(f"[score={score:.3f}] doc={doc.metadata.get('doc_name')} page={doc.metadata.get('page')} type={doc.metadata.get('type')}")
        print(doc.page_content[:200])
        print("-" * 40)

    return results


# 사용 예시:
search("군인 해택 휴양시설알려줘")
# search("휴가 관련 표", type_filter="table")
# search("기차 할인 안내 이미지", type_filter="image")

[score=0.585] doc=사병_길라잡이.pdf page=23 type=text
2026 병 복지 길라잡이 23
 • 국군복지단 휴양시설 현황
구분
시 설 명
위 치
전화번호(군)
전화번호(일반)
직영
서귀포 호텔
제주 서귀포시
960-7703
064-738-0123
화진포 콘도
강원 고성군
960-7706
033-682-0500
청간정 콘도
강원 고성군
822-6470
033-631-9331
송 정 콘도
강원 강릉시
940-38
----------------------------------------
[score=0.546] doc=사병_길라잡이.pdf page=22 type=text
Part 01 생활편의 분야
22 2026 병 복지 길라잡이
휴양시설 이용
이용대상 / 방법 및 혜택
 • 이용대상 : 현역병, 배우자 및 그 직계 존·비속
 * 가족의 경우 가족관계 증빙서류, 신분증 또는 국방가족 모바일증명 제시
 * 국방가족 모바일증명은 국군복지포털 홈페이지를 이용하여 등록
 • 국군복지단 휴양시설 이용방법
 - 국군복지포털 홈페이지
----------------------------------------
[score=0.545] doc=초급간부_길라잡이.pdf page=35 type=text
34
2026 초급간부 길라잡이
•국군복지단 휴양시설 현황
구분
시 설 명
위 치
전화번호(군)
전화번호(일반)
직영
서귀포 호텔
제주 서귀포시
960-7703
064-738-0123
화진포 콘도
강원 고성군
960-7706
033-682-0500
청간정 콘도
강원 고성군
988-7873
033-631-9331
송정 콘도
강원 강릉시
940-3881
----------------------------------------
[score=0.528] doc=초급간부_길라잡이.pdf page=34 type=text
02
Part
생
활
편
의

분
야
33
2026 초급간부 길라잡이
•국군복지단 초급간부전용 객실예약 이용방법
- 국군복지포털 호텔/콘도/컨벤션-객실예약-‘초급간부전용 객실예약’ 활용
- 국군복지단 휴양시설 세부 이용절차
신청/접수
•인터넷 : 국군복지단 홈페이지(www.welfare.mil.kr)
 * 스마트폰 : 국군복지포털 앱 ⇨ 호텔/콘도
----------------------------------------
[score=0.519] doc=초급간부_길라잡이.pdf page=35 type=table
이 표는 국군복지단 관련 숙박/휴양시설의 목록을 정리한 것으로, 컬럼은 `구분`, `시설명`, `위치`, `전화번호(군)`, `전화번호(일반)`을 의미합니다. 서귀포 호텔, 화진포·청간정·송정·대천 콘도 등 단일 시설 5곳과, 한화·금호·소노·켄싱턴 등 제휴 리조트 브랜드 및 해당 지점 지역이 함께 수록되어 있습니다. 주요 연락처로는 서귀포 호텔 960-7
----------------------------------------

[(Document(metadata={'doc_name': '사병_길라잡이.pdf', 'page': 23, 'type': 'text', '_id': 'fb4aa98d-c931-5260-82b6-e1fa8da946b5', '_collection_name': 'guidance_vectordb'}, page_content='2026 병 복지 길라잡이 23\n • 국군복지단 휴양시설 현황\n구분\n시 설 명\n위 치\n전화번호(군)\n전화번호(일반)\n직영\n서귀포 호텔\n제주 서귀포시\n960-7703\n064-738-0123\n화진포 콘도\n강원 고성군 \n960-7706\n033-682-0500\n청간정 콘도\n강원 고성군 \n822-6470\n033-631-9331\n송 정 콘도\n강원 강릉시 \n940-3881\n033-652-7573\n대 천 콘도\n충남 보령시 \n960-7705\n041-932-6305\n민영\n한 화\n설악, 용인, 대천, 산정호수, \n해운대, 경주, 제주, 평창, 거제\n국군복지단\n예약실\n984-6584\n국군복지단\n예약실\n1577-9800\n내선 “1번”\n금 호\n통영, 화순, 설악, 제주, 아산\n소 노\n설악, 경주, 단양, 홍천, 양양, \n변산, 거제, 삼척, 진도, 여수, \n고양(호텔), 양평\n켄싱턴\n남원, 설악비치, 충주, 경주,\n가평, 설악밸리, 하동, 서귀포\n무 주\n전북무주\n리 솜\n안면도\n엘도라도\n전남신안\n샤인빌(소노캄)\n제주\n보 광\n제주\n웰리힐리\n강원횡성\n영랑호\n강원 속초\n현대수\n강원 속초\n • 각 군 휴양시설 이용방법 : 각 군 홈페이지 참조\n구분\n시 설 명\n홈페이지 주소\n국방부\n국방컨벤션(웨딩)\nwww.mndconvention.co.kr\n육군\n로카우스 호텔, 계룡스파텔\nwelfare.army.mil.kr\n해군\n해군호텔(서울, 평택, 제주), \n해군회관(진해)\nwelfare.navy.mil.kr\n공군\n공군호텔\nwww.airforcehotel.co.kr\n그린나래호텔\nwww.guerinnarae.com\n해병대\n밀리토피아호텔 바이마린(해병대호텔)\nwww.militopiahotelbymarine.com'),
  0.5854219),
 (Document(metadata={'doc_name': '사병_길라잡이.pdf', 'page': 22, 'type': 'text', '_id': '40497236-80dc-5f46-b78d-a7b918de24d9', '_collection_name': 'guidance_vectordb'}, page_content='Part 01 생활편의 분야\n22 2026 병 복지 길라잡이\n휴양시설 이용\n이용대상 / 방법 및 혜택\n • 이용대상 : 현역병, 배우자 및 그 직계 존·비속\n * 가족의 경우 가족관계 증빙서류, 신분증 또는 국방가족 모바일증명 제시\n * 국방가족 모바일증명은 국군복지포털 홈페이지를 이용하여 등록\n • 국군복지단 휴양시설 이용방법\n - 국군복지포털 홈페이지 메인화면에 ‘병사전용 회원가입 메뉴’ 활용\n * 최소한의 정보(군번, 군구분, 성명 입력 → ID / PW 생성)로 가입 가능\n - 국군복지단 휴양시설 세부 이용절차\n신청/\n접수\n∙ 인터넷 : 국군복지포털 홈페이지(http://www.welfare.mil.kr)\n* 스마트폰 : 국군복지포털 앱 ⇨ 호텔/콘도 ⇨ 현역병 전용 예약\n∙ 예약/회원가입 : 군 984-6584, 일반 1577-9800 내선 1번\n신청시기\n예약확정\n∙ 직영 시설 이용일 기준 30일 전 00시~8일 전 23:59까지 신청\n 민영 시설 이용일 기준 30일 전 00시∼22일 전 23:59\n예약자 \n통보\n∙ 예약확정 시 이용 안내문자 발송\n1회 숙박\n가능기간\n∙ 성수기/ 비수기 주말(금, 토) : 2박 3일(제주지역: 3박 4일)\n∙ 비수기 평일(일 ~ 목) : 4박 5일\n * 여름⋅겨울 성수기(스키장운영 민영콘도만 해당) 기간 중\n 시설 이용은 1인 1회 / 기타 기간은 월 2회\n \n • 혜 택\n - 국군복지단 휴양시설(민영, 직영) 병사(가족) 대상 객실 우선 할당\n * 현역 이용 객실의 20%\n * 예약방법: 국군복지포털 홈페이지 내 ‘현역병 전용 객실예약’ 활용\n - 국군복지단 직영 휴양시설 성수기를 제외한 기간 중 평일 객실 30% 할인 \n * 현역병 본인 투숙 시\n * 직영콘도별 성수기 기간 : (제주) 매년 12월 1일 ∼ 2월 29일 /\n (제주 외) 매년 7월 1일 ~ 8월 31일'),
  0.54578745),
 (Document(metadata={'doc_name': '초급간부_길라잡이.pdf', 'page': 35, 'type': 'text', '_id': '1ae0cc80-62b3-5c57-9da7-42a7b205c3cf', '_collection_name': 'guidance_vectordb'}, page_content='34 \n2026 초급간부 길라잡이\n•국군복지단 휴양시설 현황\n구분\n시 설 명\n위 치\n전화번호(군)\n전화번호(일반)\n직영\n서귀포 호텔\n제주 서귀포시\n960-7703\n064-738-0123\n화진포 콘도\n강원 고성군 \n960-7706\n033-682-0500\n청간정 콘도\n강원 고성군 \n988-7873\n033-631-9331\n송정 콘도\n강원 강릉시 \n940-3881\n033-652-7573\n대천 콘도\n충남 보령시 \n960-7705\n041-932-6305\n민영\n한 화\n 거제, 경주, 대천, \n산정호수, 설악, 용인, \n제주, 평창, 해운대\n국군복지단\n예약실\n984-6499\n국군복지단\n예약실\n1577-9800\n금 호\n 통영, 화순, 설악, 제주, 아산\n소 노\n 경주, 거제, 고양, 단양,\n변산, 삼척, 설악, 진도,\n양양, 양평, 여수, 홍천\n켄싱턴\n남원, 설악비치, 충주, \n경주, 가평, 설악밸리, \n하동, 서귀포\n무 주\n전북 무주\n리 솜\n안면도\n엘도라도\n전남 신안\n샤인빌\n제주\n보 광\n제주\n웰리힐리\n강원 횡성\n영랑호\n강원 속초\n현대수\n강원 속초\n국방부 복지정책과 복지운영담당 | 900-6617\n담당부서'),
  0.5448516),
 (Document(metadata={'doc_name': '초급간부_길라잡이.pdf', 'page': 34, 'type': 'text', '_id': '58b67cb3-15b4-5cad-9036-b93e98e25e44', '_collection_name': 'guidance_vectordb'}, page_content='02\nPart\n생\n활\n편\n의\n \n분\n야\n33 \n2026 초급간부 길라잡이\n•국군복지단 초급간부전용 객실예약 이용방법\n- \x07국군복지포털 호텔/콘도/컨벤션-객실예약-‘초급간부전용 객실예약’ 활용\n- 국군복지단 휴양시설 세부 이용절차\n신청/접수\n•\x07인터넷 : 국군복지단 홈페이지(www.welfare.mil.kr)\n * 스마트폰 : 국군복지포털 앱 ⇨ 호텔/콘도 ⇨ 초급간부 전용 예약\n•\x07예약/회원가입 : 군 984-6499, 일반 1577-9800 내선 1번\n신청시기/ \n예약확정\n•\x07기간 : 이용일 기준 50일 전일 00:00 ∼ 30일 전일 23:59\n•\x07예약확정 확인 : 이용일 기준 29일 전일 10:00 확정(복지포털 확인)\n * 추첨제 탈락 시 : 일반 예약신청(점수제) 자동 전환 / 자동 전환 취소 가능\n예약자 통보\n•\x07예약확정 시 이용 안내문자 발송\n1회 숙박\n가능기간\n•\x07성수기/비수기 주말(금, 토) : 2박 3일(제주지역: 3박 4일)\n•\x07비수기 평일(일 ~ 목) : 4박 5일\n * \x07여름·겨울 성수기(스키장운영 민영콘도만 해당) 기간 중 시설 이용은 1인 1회 / \n기타 기간은 월 2회 \n•비수기 잔여객실 회원초대제도\n- 현역간부, 가족(직계존비속) 외 비회원을 초대하여 단독 이용기회 \n* \x07예약기간 : 내륙-이용일 기준 10일 전 ~ 4일 전, 제주-이용일 기준 25일 전 ~ 4일 전 \n* 요금적용 : 회원요금과 동일(직영시설의 경우 부가가치세 10% 추가)\n* 예약방법 : 잔여객실 예약에서 ‘초대함’ 선택 및 실제 이용자 입력\n* 초대한도 : 연 5회\n•각 군 휴양시설 이용방법 : 각 군 홈페이지 참조\n구분\n시 설 명\n홈페이지\n국방부\n국방컨벤션\nwww.mndconvention.co.kr\n육군\n계룡스파텔, ROKAUS호텔\nwelfare.army.mil.kr\n해군\n해군호텔(서울, 평택, 제주), \n해군회관(진해)\nwelfare.navy.mil.kr\n공군\n공군호텔\nwww.airforcehotel.co.kr\n그린나래호텔\nwww.guerinnarae.com\n해병대\n밀리토피아 호텔 바이마린\nwww.militopiahotelbymarine.com\n* 현역 결혼, 가족 행사시 컨벤션 할인 혜택 : 각 기관 홈페이지 확인'),
  0.5275589),
 (Document(metadata={'doc_name': '초급간부_길라잡이.pdf', 'page': 35, 'type': 'table', 'table_markdown': '| 구분 | 시 설 명 | 위 치 | 전화번호(군) | 전화번호(일반) |\n| --- | --- | --- | --- | --- |\n|  | 서귀포 호텔 | 제주 서귀포시 | 960-7703 |  |\n|  | 화진포 콘도 | 강원 고성군 | 960-7706 |  |\n|  | 청간정 콘도 | 강원 고성군 | 988-7873 |  |\n|  | 송정 콘도 | 강원 강릉시 | 940-3881 |  |\n|  | 대천 콘도 | 충남 보령시 | 960-7705 |  |\n|  | 한 화 | 거제, 경주, 대천,\n산정호수, 설악, 용인,\n제주, 평창, 해운대 | 국군복지단\n예약실\n984-6499 |  |\n|  | 금 호 | 통영, 화순, 설악, 제주, 아산 |  |  |\n|  | 소 노 | 경주, 거제, 고양, 단양,\n변산, 삼척, 설악, 진도,\n양양, 양평, 여수, 홍천 |  |  |\n|  | 켄싱턴 | 남원, 설악비치, 충주,\n경주, 가평, 설악밸리,\n하동, 서귀포 |  |  |\n|  | 무 주 | 전북 무주 |  |  |\n|  | 리 솜 | 안면도 |  |  |\n|  | 엘도라도 | 전남 신안 |  |  |\n|  | 샤인빌 | 제주 |  |  |\n|  | 보 광 | 제주 |  |  |\n|  | 웰리힐리 | 강원 횡성 |  |  |\n|  | 영랑호 | 강원 속초 |  |  |\n|  | 현대수 | 강원 속초 |  |  |', 'summary': '이 표는 국군복지단 관련 숙박/휴양시설의 목록을 정리한 것으로, 컬럼은 `구분`, `시설명`, `위치`, `전화번호(군)`, `전화번호(일반)`을 의미합니다. 서귀포 호텔, 화진포·청간정·송정·대천 콘도 등 단일 시설 5곳과, 한화·금호·소노·켄싱턴 등 제휴 리조트 브랜드 및 해당 지점 지역이 함께 수록되어 있습니다. 주요 연락처로는 서귀포 호텔 960-7703, 화진포 콘도 960-7706, 청간정 콘도 988-7873, 송정 콘도 940-3881, 대천 콘도 960-7705가 있으며, 한화는 국군복지단 예약실 984-6499로 안내됩니다.', '_id': '7f46223c-b7fa-5103-9b15-f793fae79e32', '_collection_name': 'guidance_vectordb'}, page_content='이 표는 국군복지단 관련 숙박/휴양시설의 목록을 정리한 것으로, 컬럼은 `구분`, `시설명`, `위치`, `전화번호(군)`, `전화번호(일반)`을 의미합니다. 서귀포 호텔, 화진포·청간정·송정·대천 콘도 등 단일 시설 5곳과, 한화·금호·소노·켄싱턴 등 제휴 리조트 브랜드 및 해당 지점 지역이 함께 수록되어 있습니다. 주요 연락처로는 서귀포 호텔 960-7703, 화진포 콘도 960-7706, 청간정 콘도 988-7873, 송정 콘도 940-3881, 대천 콘도 960-7705가 있으며, 한화는 국군복지단 예약실 984-6499로 안내됩니다.'),
  0.51891375)]

In [48]:
# ! uv pip install nbconvert

In [ ]:
# ! jupyter nbconvert --to script guidance_loader.ipynb
# guidance_loader.ipynb -> guidance_loader.py

In [6]:
##################################################
# vector DB 연결
# retriever 생성
##################################################

from pathlib import Path
import glob

from langchain_openai import OpenAIEmbeddings
from langchain_qdrant import QdrantVectorStore
from qdrant_client import QdrantClient
from qdrant_client.models import Distance, VectorParams

from guidance_loader import build_documents_for_pdf, GUIDANCE_DIR  # 실제 존재하는 함수/상수로 교체

EMBED_MODEL = "text-embedding-3-large"
EMBED_DIM = 3072


def get_vectorstore(collection_name: str = "guidance_vectordb", force_rebuild: bool = False):
    """
    벡터스토어에 연결한다.
    - 컬렉션이 이미 있으면: 연결만 하고 재사용 (재적재로 인한 시간/비용 낭비 방지)
    - 컬렉션이 없으면: 새로 만들고 PDF들을 적재
    - force_rebuild=True: 기존 컬렉션을 지우고 처음부터 다시 적재
    """
    dense_embeddings = OpenAIEmbeddings(model=EMBED_MODEL)
    client = QdrantClient(url="http://localhost:6333")

    collection_exists = client.collection_exists(collection_name)

    if force_rebuild and collection_exists:
        client.delete_collection(collection_name=collection_name)
        collection_exists = False

    if not collection_exists:
        client.create_collection(
            collection_name=collection_name,
            vectors_config=VectorParams(size=EMBED_DIM, distance=Distance.COSINE),
        )

    vectorstore = QdrantVectorStore(
        client=client,
        collection_name=collection_name,
        embedding=dense_embeddings,
    )

    # 새로 만든 컬렉션일 때만 적재 (기존 컬렉션 있으면 스킵)
    if not collection_exists:
        _ingest_documents(vectorstore)

    return vectorstore


def _ingest_documents(vectorstore: QdrantVectorStore, directory: str = GUIDANCE_DIR, batch_size: int = 100):
    """guidance_loader.ipynb의 build_documents_for_pdf + upsert 로직을 그대로 재사용"""
    paths = sorted(glob.glob(str(Path(directory) / "*.pdf")))
    print(f"'{directory}'에서 PDF {len(paths)}개 발견, 적재 시작\n")

    total_chunks = 0
    for pdf_path in paths:
        documents, ids = build_documents_for_pdf(pdf_path)
        for i in range(0, len(documents), batch_size):
            vectorstore.add_documents(
                documents=documents[i:i + batch_size],
                ids=ids[i:i + batch_size],
            )
        total_chunks += len(documents)
        print()

    print(f"완료: PDF {len(paths)}개 / 총 {total_chunks}개 청크 적재")


def get_retriever(vectorstore, k: int = 5):
    retriever = vectorstore.as_retriever(
        search_kwargs={"k": k}
    )
    return retriever

'guidance_vectordb' collection이 이미 존재합니다.
'./길라잡이' 안에서 발견된 PDF 2개
 - 길라잡이\사병_길라잡이.pdf
 - 길라잡이\초급간부_길라잡이.pdf
'./길라잡이'에서 PDF 2개 발견, 적재 시작

[사병_길라잡이.pdf] 텍스트 84 / 표 59 → 총 143개
  upsert 진행: 100/143
  upsert 진행: 143/143

[초급간부_길라잡이.pdf] 텍스트 92 / 표 102 → 총 194개
  upsert 진행: 100/194
  upsert 진행: 194/194

완료: PDF 2개 / 총 337개 청크 적재

In [7]:
vectorstore = get_vectorstore()
print(vectorstore)
retriever = get_retriever(vectorstore)
print(retriever)

<langchain_qdrant.qdrant.QdrantVectorStore object at 0x000001CFF4193890>
tags=['QdrantVectorStore', 'OpenAIEmbeddings'] vectorstore=<langchain_qdrant.qdrant.QdrantVectorStore object at 0x000001CFF4193890> search_kwargs={'k': 5}

In [8]:
################################################################################
# 평가할 RAG Chain
################################################################################

from langchain_core.prompts import ChatPromptTemplate
from langchain_core.runnables import RunnablePassthrough, RunnableLambda
from langchain_core.output_parsers import StrOutputParser
from langchain_core.documents import Document
from langchain_openai import ChatOpenAI

vectorstore = get_vectorstore()
retriever = get_retriever(vectorstore)

prompt_txt = """<instruction>
당신은 정보제공을 목적으로하는 유능한 AI Assistant 입니다.
주어진 context의 내용을 기반으로 질문에 답변을 합니다.
Context에 질문에 대한 명확한 정보가 있는 경우 그것을 바탕으로 답변을 합니다.
Context에 질문에 대한 명확한 정보가 없는 경우 "정보가 부족해 답을 할 수없습니다." 라고 답합니다.
절대 추측이나 일반 상식을 바탕으로 답을 하거나 Context 없는 내용을 만들어서 답변해서는 안됩니다.
</instruction>
<context>
{context}
</context>
<question>
{query}
</question>
"""
prompt = ChatPromptTemplate.from_template(template=prompt_txt)

model = ChatOpenAI(model="gpt-5.4-mini")
parser = StrOutputParser()


def format_docs_for_prompt(documents: list[Document]) -> str:
    """LLM 프롬프트({context})용: 문서들을 하나의 문자열로 합침 (doc_name/page도 같이 표기)"""
    parts = []
    for doc in documents:
        meta = doc.metadata
        header = f"[{meta.get('doc_name', '')} p.{meta.get('page', '')}]"
        parts.append(f"{header}\n{doc.page_content}")
    return "\n\n---\n\n".join(parts)


def format_docs_for_ragas(documents: list[Document]) -> list[str]:
    """RAGAS 평가용: 검색된 문서 각각의 내용을 list[str]로 추출"""
    return [doc.page_content for doc in documents]


def build_prompt_input(state: dict) -> dict:
    """검색 결과({'documents':..., 'query':...})를 prompt 입력({'context':str, 'query':str})으로 변환"""
    return {
        "context": format_docs_for_prompt(state["documents"]),
        "query": state["query"],
    }


# 1단계: 질문으로 검색 → 원본 Document 리스트 + 질문 보존 (retriever는 여기서 1회만 호출됨)
retrieve_step = {
    "documents": retriever,
    "query": RunnablePassthrough(),
}

# RAG 체인 -> RAG 평가 데이터셋을 만드는 RAG Chain -> 최종응답: LLM 응답(str), 검색한 문서들(list[str]), 질문(str)
chain = (
    RunnablePassthrough()  # dict | dict 가 파이썬 dict 병합 연산으로 취급되는 것을 막기 위해 필요
    | retrieve_step
    | {
        "response": RunnableLambda(build_prompt_input) | prompt | model | parser,
        "retrieved_context": RunnableLambda(lambda state: format_docs_for_ragas(state["documents"])),
        "query": RunnableLambda(lambda state: state["query"]),
    }
)

In [9]:
res = chain.invoke("병장의 월급은?")

In [10]:
res["response"]

'병장의 월급은 **1,500,000원**입니다.'

In [11]:
res["retrieved_context"]

['Part 01 생활편의 분야\n6 2026 병 복지 길라잡이\n보 수\n봉 급\n • 계급별 지급액\n 단위 : 원\n \n이병\n일병\n상병\n병장\n750,000\n900,000\n1,200,000\n1,500,000\n • 병 봉급 인상\n 단위 : 원\n연도\n계급\n’21년\n’22년\n’23년\n’24년\n’25~’26년\n병 장 \n608,500\n676,100\n1,000,000\n1,250,000\n1,500,000\n상 병 \n549,200\n610,200\n800,000\n1,000,000\n1,200,000\n일 병\n496,900\n552,100\n680,000\n800,000\n900,000\n이 병\n459,100\n510,100\n600,000\n640,000\n750,000\n인상율(병장)\n12.5%\n11.1%\n47.9%\n25%\n20%\n* 병역의무 이행자의 보상과 예우를 위해 병 봉급과 자산형성프로그램을 결합하여\n’25년까지 병장 기준 200만원 이상으로 인상\n수 당\n단위 : 원\n \n구 분\n지급 기준\n금액\n특수지\n근 무\n수 당\n갑\n・비무장지대, 서해5도, 울릉도, 접적 해역 상주 근무자\n * 가산금 : 서해5도 40,000원, 비무장지대 및 \n북방한계선 인접해역 20,000원\n25,000 \n(가산금별도)\n을\n・GOP, 해안초소, 해발 800m 이상 고지대 상주 근무자\n * 가산금 : 10,000원(GOP / 해안초소)\n20,000\n(가산금별도)\n항 공\n수 당\n을\n・항공기 동승근무자\n40,000 \n함 정\n수 당\n을\n・전투함 및 지원함 승무원\n * 함정출동가산금 : 1일 4,000원\n32,700 \n(가산금별도)\n병\n・수륙양용궤도차량 승무원\n32,700 \npart 01\n생활편의 분야\n▶▶▶ 병 복지혜택 이렇게 다양합니다',
 '이 표는 **계급별 연도(’21~’26년) 급여 수준과 병장 급여 인상률**을 비교한 자료입니다. 행은 **병장·상병·일병·이병**의 월급이며, 열은 **’21년, ’22년, ’23년, ’24년, ’25~’26년**의 금액 변화를 보여줍니다. 주요 수치로 병장 급여는 **60.85만 원 → 67.61만 원 → 100만 원 → 125만 원 → 150만 원**, 상병은 **54.92만 원 → 61.02만 원 → 80만 원 → 100만 원 → 120만 원**, 일병은 **49.69만 원 → 55.21만 원 → 68만 원 → 80만 원 → 90만 원**, 이병은 **45.91만 원 → 51.01만 원 → 60만 원 → 64만 원 → 75만 원**으로 증가합니다. 또한 병장 인상률은 **12.5%, 11.1%, 47.9%, 25%, 20%**로 표시되어 있습니다.',
 '2026 병 복지 길라잡이 7\n수 당(계속)\n 단위 : 원 / 월\n \n구 분\n지급 기준\n금액\n위험\n근무\n수당\n갑\n・40m 이상 해난구조 및 특수잠수 작업\n240,240\n・고공 낙하산 강하자\n138,800\n・불발탄처리 및 탄약 기능 시험자, 지뢰제거 작전 투입\n118,800\n을\n・항공기/기구 강하자\n85,000 \n・헬기 레펠 및 F/R 강하자\n55,000\n・상륙 임무자(해병대)\n50,000\n병\n・특수전류분야 종사자, 탄약개수의 특수분야 종사자\n・월 1회 모형탑 낙하자, 컨테이너 크레인 운용자\n・유해발굴 / 감식업무자, 중장비 수송차량 운전자\n18,000\n위험근무수당 \n가산금\n・위험근무수당을 지급받는 특전사, 해병대, 해군(UDT/SSU)과 각 군의 \n폭발물처리반에 근무하는 군인이 특수임무를 위해 야외 출동 시 1일 \n3,000원 지급\n해파수당\n・해외파견근무수당 지급규정에 따라 임무・환경・등급・지역 등 고려 \n등급별 지급\n * 월 지급 기준액(미합중국 달러) : 1,474달러\n여 비\n • 정기휴가비(급지별) * ’25년 식비 : 7,000원 / 1식\n단위 : 원\n \n구 분\n휴가여비(왕복)\n전역귀가여비(편도)\n1 급지 (451Km 이상)\n152,200\n76,100\n2 급지 (450Km까지)\n138,400\n69,200\n3 급지 (400Km까지)\n110,600\n55,300\n4 급지 (350Km까지)\n96,800\n48,400\n5 급지 (300Km까지)\n83,000\n41,500\n6 급지 (250Km까지)\n69,200\n34,600\n7 급지 (200Km까지)\n46,800\n23,400\n8 급지 (150Km까지)\n33,000\n16,500\n9 급지 (100Km까지)\n22,000\n11,000\n10 급지 (50Km까지)\n13,800\n6,900\n도서가산금\n50해리 미만\n49,800\n24,900\n50해리 이상\n145,560\n89,280\n백령(울릉)도\n175,720\n111,360\n* 교통비 기준 단가 인상 : Km당 132원→138원, 식비 : 7,000원 / 1식 \n • 도서가산금 : (기존) 귀향지만 적용, (개선) 출발지까지 추가',
 'Part 01 생활편의 분야\n8 2026 병 복지 길라잡이\n병 급여(봉급/ 수당 등) 확인방법 안내\n • 급여 지급 일자별 지급항목\n - 매월 10일 : 봉급, 수당, 휴가ㆍ전역비, 병 일용품비\n - 매월 25일 : 신규 입대자 봉급, 수당, 휴가ㆍ전역비\n • 급여지급 확인방법 * 아래 2가지 사항 중 선택\n ①국군재정관리단 인트라넷 국방급여포털 접속 후 조회 \n ②국방급여포털(앱) 접속 / 로그인 후 급여명세서 확인\n • 급여 미지급 / 착오지급 발생 시 문의\n - 주요 착오 / 미지급 사례\n \n구 분\n내 용\n봉 급\n・진급을 하였으나 전 계급으로 급여가 지급된 경우\n ☞ 소속부대에서 진급명령 미발령·지연한 경우로서, 명령 발령 시 다음달 \n급여에 소급지급\n휴가 / \n전역비\n・진급월 휴가비 미지급된 사례\n ☞ 진급 당시 입실 중이거나, 군병원 퇴원 이후 퇴원명령 처리가 지연된 경우로서 \n명령발령, 급여지급 조치 후 당월 25일 또는 다음달 10일 급여 지급 시 소급지급\n ☞ 제주도, 연평도 등 도서지역 거주 또는 근무인원의 경우 소속부대 인사/\n 재정부서에서 항구설정 必, 항구 설정 및 휴가비 추가회수등록시 소급지급\n - 문의방법\n • 1차 : 인사 명령(입대ㆍ진급ㆍ전역) 발령, 급지 설정 여부 확인(소속부대 인사부서)\n • 2차 : 인사 명령 발령에 근거한 국방통합급여정보체계(DIPIS) 반영 여부 확인\n * 소속부대 인사 / 재정부서 확인(육군 : 재정, 해·공군·해병대 : 인사부서)\n •기타 안내사항\n - 급여계좌 변경\n • 변경 시기 : 훈련소 및 신병교육대 수료 후 소속부대(자대)에서 변경\n * 훈련소, 신병교육기관에서 임의 변경 불가: 소속 부대(자대)에서 변경\n • 변경방법: 매월 말일까지 개인이 급여포탈에서 직접신청 또는 소속\n부대 인사ㆍ재정부서 급여업무 담당자에게 변경 요청',
 '6 \n 기본급 및 각종 수당 인상 \n \n•(기본급) 초급간부 기본급 6.6% 인상(하사·중사·소위·중위)\n구 분\n소 위\n중 위\n하 사\n중 사\n’25년\n2,017,300원\n2,163,900원\n2,000,900원\n2,046,400원\n’26년\n2,150,400원\n2,306,700원\n2,133,000원\n2,181,500원\n* 기타 계급은 3.5% 인상\n \n•(특수/위험근무수당) 핵심전투인력 수당 신설 및 인상\n구 분\n특수근무수당\n위험근무수당\n신설\n· 간호조무부사관 장려수당\n· 국방대학교 특정직 교수 수당\n· 방사선 취급 근무자 위험근무수당\n· 운용시험평가관 위험근무수당\n· 조사본부 과학수사연구소 \n 위험근무수당\n인상/\n확대\n· 수상함 함정근무수당 10%\n· 중요직무급 위험·특수지근무수당과 병급\n·\x07 \x07장려수당 1호(특수무기), 5호(위성운용), \n8호(부사관) 지급대상 확대\n· 급유통제사 항공수당 급호 인상\n· 야간비행 출동가산금 확대\n· 민원업무수당 인상\n· 갑3호(대테러부대) 지급대상 확대\n \n•(시간외근무수당) 상한시간 예외직위 최신화\n - 의무후송항공대, 해상초계기 운용요원, 우도경비대 등\n * 시간외근무 상한 시간은 동일(GP 200시간, GOP·해강안·함정 등 150시간)\n \n•(비상근무수당) 일 8,000원, 월 120,000원→일 16,000원, 월 180,000원\n \n•(업무대행수당) 육아·질병휴직 → 대상 확대(모든 휴직 업무대행자)\n 당직근무비 인상\n \n•평일 : 2만원 → 3만원 / 휴일 4만원 → 10만원\n 장병e음 플랫폼 서비스 개시 : ’26. 2월\n \n•\x07인사, 행정, 복지 등 여러 서비스를 통합·연결하여 모바일 환경에서 일괄 \n제공하는 플랫폼 개시\n’26년도에는 이렇게 바뀝니다!\n2026 초급간부 길라잡이']

# 4. RAGAS 를 이용해 평가를 위한 합성 데이터 셋 만들기

- 평가 데이터셋 구성
  - `user_input`: 사용자 질문
  - `retrieved_contexts`: Vectorstore에서 검색한 context
  - `response`: LLM의 응답
  - `reference`: 정답

## 4.1 TestsetGenerator
- **문서(retrieved_contexts)를 기준**으로 **질문**, **정답** 을 생성한다.
- 평가할 LLM으로 생성된 질문을 넣어 답변을 추출하여 데이터셋을 구성한다.


> **주의**
> - TestsetGenerator import 시 `No Module named langchain_community.chat_models.vertexai` Error 발생 
> - RAGAS와 langchain-community의 버전 호환성 문제 때문에 발생한다.
> - 해결
>   1. langchain_google_vertexai 설치
>       - `!uv pip install langchain_google_vertexai`
>   2. `.venv\Lib\site-packages\langchain_community\chat_models` 디렉토리 아래 `vertexai.py` 파일을 만들고 아래 코드를 > 넣는다.
>    ```python
>       try:
>          from langchain_google_vertexai import ChatVertexAI
>       except ImportError:
>           class ChatVertexAI:
>               def __init__(self, *args, **kwargs):
>                   raise ImportError(
>                       "ChatVertexAI requires langchain-google-vertexai. "
>                       "Install with: pip install langchain-google-vertexai"
>                   )
>    ```

In [12]:
# !uv pip install langchain_google_vertexai

In [31]:
# 주피터노트북 환경에서 비동기적 처리 위해 
# script(.py) 로 작성할 경우는 필요 없다.

import nest_asyncio
nest_asyncio.apply()

In [13]:
from ragas.testset import TestsetGenerator

c:\Users\Playdata\SKN\SKN31-3rd-2Team\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [14]:
#
# testset -> Context들(문서들) - [질문 - 정답답변 + (Retriever가 찾은 문서 + LLM 응답: chain에서 생성)]
# 1. Context(문서들)을 추출 - TestsetGenerator -> 질문과 정답 답변 생성

import random

# 데이터셋을 생성할 때 사용할 Context를 추출
client = QdrantClient(url="http://localhost:6333")
COLLECTION_NAME = "guidance_vectordb"

info = client.get_collection(COLLECTION_NAME)
total_docs = info.points_count

results, _ = client.scroll(
    collection_name=COLLECTION_NAME,
    limit=total_docs,
)

# random하게 k(5)개를 sampling
sample_docs:"list[PointStruct]" =random.sample(results, 5) # 리스트에서 랜덤하게 k(5)개를 추출

# PointStruct - payload: page_content, metadata
# page_content만 추출해서 list[str]
docs = [point.payload['page_content'] for point in sample_docs]

In [15]:
total_docs

337

In [16]:
sample_docs

[Record(id='60fe2294-6088-5447-95a5-5742cc5b3031', payload={'page_content': '01\nPart\n자\n기\n개\n발\n \n및\n \n전\n직\n지\n원\n \n분\n야\n67 \n03\nPart\n2026 초급간부 길라잡이\n-③-Ⅵ\n국민내일배움카드(고용노동부) \n-③-Ⅶ\n기 타\n 개 요 \n \x07전 생애에 걸친 직무수행능력 습득·향상을 위해 국민 스스로 직업능력개발훈련을 \n실시할 수 있도록 훈련비 등 지원\n* 단, 관련 법령에 따라 공무원, 군인 등 일부 대상 제외\n* \x07군인의 경우, 국민 평생 직업능력 개발법 시행령 제6조 및 군인사법 시행령 제60조의2에 \n따라 단기복무 전역예정자의 경우 예외적으로 지원\n 주요내용\n •(신청자격) 신청일 기준 ① 5년 미만의 기간동안 현역으로 복무하고, \n ② 전역예정일까지의 기간이 6개월 이하인 장교·준사관 또는 부사관\n •(지원내용) 계좌발급일로부터 5년간 300만원 이내 훈련비 지원*\n* 훈련과정 직종별 취업률, 소득수준 등에 따라 훈련비 일정비율(0~55%) 자비 부담\n •(신청절차)\n신청인\n⇨\n각 군\n⇨\n관할 고용센터\n⇨\n훈련생·훈련기관\n• \x07신청서 작성 후 \n소속부대 담당자\n에게 제출\n•신청자격 확인 \n•\x07관할 고용센터에\n 추천 공문 발송\n•\x07신청인이 방문하여 \n발급절차 진행\n•\x07개인별 훈련과정 신청 \n및 실시\n* \x07(참고) 군 전직 및 취업 지원 업무에 관한 훈령 제11조의2 및 별지 제8호 서식(훈련과정) \n한국기술교육대학교(직업능력심사평가원) 등의 심사결과에 따라 지방관서의 장이 인정·\n통지하는 훈련과정\n* \x07국민내일배움카드 사업내용 및 훈련과정 등 구체적인 내용은 고용24 홈페이지 (www.work24.\ngo.kr)에서 확인\n 취업정보 제공 \n •국방일보 취업정보 게재 (매주 화요일) : (http://kookbang.dema.mil.kr)\n •온라인(인터넷)을 통한 정보확인\n - \x07국방전직교육원(www.moti.or.kr) \n - 고용부 워크넷(www.work.go.kr)\n - 중소벤처기업진흥공단(www.kosmes.or.kr)\n - 국가보훈부 제대군인지원센터(www.vnet.go.kr)\n - 나라일터(www.gojobs.go.kr) 등\n국방부 일자리정책과 취업지원정책 | 900-6635\n담당부서', 'metadata': {'doc_name': '초급간부_길라잡이.pdf', 'page': 68, 'type': 'text'}}, vector=None, shard_key=None, order_value=None),
 Record(id='46b7fd01-9002-57a2-b906-62af9d507855', payload={'page_content': '이 표는 **각 군(육군·해군·공군·해병)의 장기복무(연장복무) 선발 안내**를 정리한 것으로, 장기복무 선발계획이 **홈페이지에 게시되는 시기**와 함께 선발 준비 시 확인해야 할 사항을 담고 있습니다. 컬럼은 문서 제목 아래에 각 군별 **장교/부사관 선발계획 탑재 시기**를 구분해 적고 있으며, 육군은 장교 전반기 전년도 12월·후반기 8월, 부사관 4월, 해군은 장교·부사관 전반기 1월, 부사관 후반기 6월, 공군은 장교 전반기 2월·부사관 전반기 1월, 해병은 장교 전반기 2월·후반기 9월, 부사관 전반기 3월·후반기 10월로 제시합니다. 또한 선발절차·추진일정·평가기준 등은 매년 최신화되며, 책임감 있는 임무수행과 대인관계, 관련 자격증 취득 같은 자기개발이 중요하다고 안내합니다. 마지막으로 장기복무 문의처와 각 군의 **선발 담당 부서/연', 'metadata': {'doc_name': '초급간부_길라잡이.pdf', 'page': 13, 'type': 'table', 'table_markdown': '| 장기복무 선발 길라잡이 |  |\n| --- | --- |\n|  |  |\n| \ue28c 장기복무 선발계획 각 군 홈페이지 탑재 시기\n•육군 : 장교 전반기 전년도 12월, 후반기 8월 / 부사관 4월\n•해군 : 장교·부사관 전반기 1월 / 부사관 후반기 6월\n•공군 : 장교 전반기 2월 / 부사관 전반기 1월\n•해병 : 장교 전반기 2월, 후반기 9월 / 부사관 전반기 3월, 후반기 10월\n* 공군은 선발결과만 홈페이지 게시, 계획은 공문으로 전파\n* 각 군별 선발절차 및 추진일정, 선발방법 및 평가기준 등 탑재되어,매년 최신화되는\n세부평가 요소를 확인해서 준비 필요\n\ue28c 책임감 있는 임무수행과 부대에 기여하는 자세가 중요\n•본인 소관 업무를 책임감 있게 수행하고,\n•특 히, 부대원(상급자, 하급자, 동료)과 원만한 관계를 유지하면서,\n해당 특기/분야에서 인정하는 자격증 등을 취득하는 자기개발 활동 필요\n\ue28c 장기(연장) 복무 관련 문의사항 : 각 부대 인사참모 소관\n\ue28c 장기(연장) 복무 선발 담당 현황\n•육군 : 인사사령부 인력획득계획과 장기복무선발담당(960-7161~3)\n•해군 : 해군본부 장교인사과 장교복무/특기관리담당(910-1216)\n부사관/병인사과 부사관/병인사담당(910-1221)\n•공군 : 공군본부 장교인사과 장교경력관리담당(920-1438)\n부사관/병인사과 부사관/병인사운영담당(910-1147)\n•해병 : 해병대사 인사운영과 장교인사담당(928-3121)\n인사운영과 부사관/병인사담당(928-3122) |  |', 'summary': '이 표는 **각 군(육군·해군·공군·해병)의 장기복무(연장복무) 선발 안내**를 정리한 것으로, 장기복무 선발계획이 **홈페이지에 게시되는 시기**와 함께 선발 준비 시 확인해야 할 사항을 담고 있습니다. 컬럼은 문서 제목 아래에 각 군별 **장교/부사관 선발계획 탑재 시기**를 구분해 적고 있으며, 육군은 장교 전반기 전년도 12월·후반기 8월, 부사관 4월, 해군은 장교·부사관 전반기 1월, 부사관 후반기 6월, 공군은 장교 전반기 2월·부사관 전반기 1월, 해병은 장교 전반기 2월·후반기 9월, 부사관 전반기 3월·후반기 10월로 제시합니다. 또한 선발절차·추진일정·평가기준 등은 매년 최신화되며, 책임감 있는 임무수행과 대인관계, 관련 자격증 취득 같은 자기개발이 중요하다고 안내합니다. 마지막으로 장기복무 문의처와 각 군의 **선발 담당 부서/연'}}, vector=None, shard_key=None, order_value=None),
 Record(id='8fe0f8db-573e-5621-b02a-47a45a28e47f', payload={'page_content': '이 표는 **취업알선 서비스의 구성 내용**을 정리한 것입니다. 주요 항목으로는 **채용정보 제공**, **직무/기업분석**, **그룹별 취업컨설팅**, **희망기업 알선**이 포함되어 있어, 구직자에게 맞춤형 취업 지원을 제공하는 내용을 나타냅니다. 컬럼의 제목인 **③ 취업알선**은 전체 프로그램의 세 번째 단계 또는 항목을 의미합니다.', 'metadata': {'doc_name': '초급간부_길라잡이.pdf', 'page': 62, 'type': 'table', 'table_markdown': '| ③ 취업알선 |\n| --- |\n| •채용정보 제공\n•직무/기업분석\n•그룹별 취업컨설팅\n•희망기업 알선 |', 'summary': '이 표는 **취업알선 서비스의 구성 내용**을 정리한 것입니다. 주요 항목으로는 **채용정보 제공**, **직무/기업분석**, **그룹별 취업컨설팅**, **희망기업 알선**이 포함되어 있어, 구직자에게 맞춤형 취업 지원을 제공하는 내용을 나타냅니다. 컬럼의 제목인 **③ 취업알선**은 전체 프로그램의 세 번째 단계 또는 항목을 의미합니다.'}}, vector=None, shard_key=None, order_value=None),
 Record(id='ed40d879-bdbd-5e81-90e9-df3af6cac35e', payload={'page_content': 'Part 05 재해보상 분야\n58 2026 병 복지 길라잡이\n 재해보상금의 종류\n사망보상금, 장애보상금\n 사망보상금\n지급 대상\n • 군인이 공무 수행 중 사망한 경우, 그 유족(배우자, 자녀, 부모, 손자녀, \n조부모) 중 「민법」에 따른 상속 우선 순위자에게 지급\n지급 기준\n \n사망 구분\n보 상 기 준\n금 액\n전 사\n공무원 전체 기준소득월액 평균액× 60\n3억 4,260만원\n특수직무순직\n공무원 전체 기준소득월액 평균액× 45\n2억 5,695만원\n일반순직\n공무원 전체 기준소득월액 평균액× 24\n1억 3,704만원\n \n * ’25년 공무원 전체 기준소득월액 평균액 : 571만원 \n청구 및 지급절차\n \n순직여부 \n조사/결정\n➜\n청구서 제출\n➜\n접수\n➜\n확인/지급\n각 군 참모총장\n청구인\n국군재정관리단장/\n주소지 관할 \n지방보훈(지)청장\n국군재정관리단장\n • 각 군 전공사상심사위원회에서 순직여부 결정\n • 청구서 및 필요 구비서류를 준비하여 국군재정관리단 또는\n지방보훈(지)청에 제출\n • 국군재정관리단에서 순직여부 확인 및 지급 결정 후 청구인에게 통보\n • 국군재정관리단에서 급여액 산정 및 사망보상금 지급\n * 사망보상금 청구서는 군인연금 홈페이지에서 다운로드 가능(www.mps.mil.kr)\npart 05\n재해보상 분야\n▶▶▶ 병 복지혜택 이렇게 다양합니다', 'metadata': {'doc_name': '사병_길라잡이.pdf', 'page': 58, 'type': 'text'}}, vector=None, shard_key=None, order_value=None),
 Record(id='c1762b7a-a17b-5402-9011-c4a0b22878ad', payload={'page_content': '표에 내용이 비어 있어, 어떤 주제를 다루는지 파악할 수 없습니다. 현재 제공된 표에는 열 이름이나 데이터가 없어 요약할 수 있는 주요 항목, 수치, 또는 컬럼 의미가 없습니다. 표의 실제 내용(컬럼명과 행 데이터)을 다시 보내주시면 2~4문장으로 검색용 요약을 작성해드리겠습니다.', 'metadata': {'doc_name': '초급간부_길라잡이.pdf', 'page': 71, 'type': 'table', 'table_markdown': '|  |\n| --- |\n|  |', 'summary': '표에 내용이 비어 있어, 어떤 주제를 다루는지 파악할 수 없습니다. 현재 제공된 표에는 열 이름이나 데이터가 없어 요약할 수 있는 주요 항목, 수치, 또는 컬럼 의미가 없습니다. 표의 실제 내용(컬럼명과 행 데이터)을 다시 보내주시면 2~4문장으로 검색용 요약을 작성해드리겠습니다.'}}, vector=None, shard_key=None, order_value=None)]

In [17]:
docs

['01\nPart\n자\n기\n개\n발\n \n및\n \n전\n직\n지\n원\n \n분\n야\n67 \n03\nPart\n2026 초급간부 길라잡이\n-③-Ⅵ\n국민내일배움카드(고용노동부) \n-③-Ⅶ\n기 타\n 개 요 \n \x07전 생애에 걸친 직무수행능력 습득·향상을 위해 국민 스스로 직업능력개발훈련을 \n실시할 수 있도록 훈련비 등 지원\n* 단, 관련 법령에 따라 공무원, 군인 등 일부 대상 제외\n* \x07군인의 경우, 국민 평생 직업능력 개발법 시행령 제6조 및 군인사법 시행령 제60조의2에 \n따라 단기복무 전역예정자의 경우 예외적으로 지원\n 주요내용\n •(신청자격) 신청일 기준 ① 5년 미만의 기간동안 현역으로 복무하고, \n ② 전역예정일까지의 기간이 6개월 이하인 장교·준사관 또는 부사관\n •(지원내용) 계좌발급일로부터 5년간 300만원 이내 훈련비 지원*\n* 훈련과정 직종별 취업률, 소득수준 등에 따라 훈련비 일정비율(0~55%) 자비 부담\n •(신청절차)\n신청인\n⇨\n각 군\n⇨\n관할 고용센터\n⇨\n훈련생·훈련기관\n• \x07신청서 작성 후 \n소속부대 담당자\n에게 제출\n•신청자격 확인 \n•\x07관할 고용센터에\n 추천 공문 발송\n•\x07신청인이 방문하여 \n발급절차 진행\n•\x07개인별 훈련과정 신청 \n및 실시\n* \x07(참고) 군 전직 및 취업 지원 업무에 관한 훈령 제11조의2 및 별지 제8호 서식(훈련과정) \n한국기술교육대학교(직업능력심사평가원) 등의 심사결과에 따라 지방관서의 장이 인정·\n통지하는 훈련과정\n* \x07국민내일배움카드 사업내용 및 훈련과정 등 구체적인 내용은 고용24 홈페이지 (www.work24.\ngo.kr)에서 확인\n 취업정보 제공 \n •국방일보 취업정보 게재 (매주 화요일) : (http://kookbang.dema.mil.kr)\n •온라인(인터넷)을 통한 정보확인\n - \x07국방전직교육원(www.moti.or.kr) \n - 고용부 워크넷(www.work.go.kr)\n - 중소벤처기업진흥공단(www.kosmes.or.kr)\n - 국가보훈부 제대군인지원센터(www.vnet.go.kr)\n - 나라일터(www.gojobs.go.kr) 등\n국방부 일자리정책과 취업지원정책 | 900-6635\n담당부서',
 '이 표는 **각 군(육군·해군·공군·해병)의 장기복무(연장복무) 선발 안내**를 정리한 것으로, 장기복무 선발계획이 **홈페이지에 게시되는 시기**와 함께 선발 준비 시 확인해야 할 사항을 담고 있습니다. 컬럼은 문서 제목 아래에 각 군별 **장교/부사관 선발계획 탑재 시기**를 구분해 적고 있으며, 육군은 장교 전반기 전년도 12월·후반기 8월, 부사관 4월, 해군은 장교·부사관 전반기 1월, 부사관 후반기 6월, 공군은 장교 전반기 2월·부사관 전반기 1월, 해병은 장교 전반기 2월·후반기 9월, 부사관 전반기 3월·후반기 10월로 제시합니다. 또한 선발절차·추진일정·평가기준 등은 매년 최신화되며, 책임감 있는 임무수행과 대인관계, 관련 자격증 취득 같은 자기개발이 중요하다고 안내합니다. 마지막으로 장기복무 문의처와 각 군의 **선발 담당 부서/연',
 '이 표는 **취업알선 서비스의 구성 내용**을 정리한 것입니다. 주요 항목으로는 **채용정보 제공**, **직무/기업분석**, **그룹별 취업컨설팅**, **희망기업 알선**이 포함되어 있어, 구직자에게 맞춤형 취업 지원을 제공하는 내용을 나타냅니다. 컬럼의 제목인 **③ 취업알선**은 전체 프로그램의 세 번째 단계 또는 항목을 의미합니다.',
 'Part 05 재해보상 분야\n58 2026 병 복지 길라잡이\n 재해보상금의 종류\n사망보상금, 장애보상금\n 사망보상금\n지급 대상\n • 군인이 공무 수행 중 사망한 경우, 그 유족(배우자, 자녀, 부모, 손자녀, \n조부모) 중 「민법」에 따른 상속 우선 순위자에게 지급\n지급 기준\n \n사망 구분\n보 상 기 준\n금 액\n전 사\n공무원 전체 기준소득월액 평균액× 60\n3억 4,260만원\n특수직무순직\n공무원 전체 기준소득월액 평균액× 45\n2억 5,695만원\n일반순직\n공무원 전체 기준소득월액 평균액× 24\n1억 3,704만원\n \n * ’25년 공무원 전체 기준소득월액 평균액 : 571만원 \n청구 및 지급절차\n \n순직여부 \n조사/결정\n➜\n청구서 제출\n➜\n접수\n➜\n확인/지급\n각 군 참모총장\n청구인\n국군재정관리단장/\n주소지 관할 \n지방보훈(지)청장\n국군재정관리단장\n • 각 군 전공사상심사위원회에서 순직여부 결정\n • 청구서 및 필요 구비서류를 준비하여 국군재정관리단 또는\n지방보훈(지)청에 제출\n • 국군재정관리단에서 순직여부 확인 및 지급 결정 후 청구인에게 통보\n • 국군재정관리단에서 급여액 산정 및 사망보상금 지급\n * 사망보상금 청구서는 군인연금 홈페이지에서 다운로드 가능(www.mps.mil.kr)\npart 05\n재해보상 분야\n▶▶▶ 병 복지혜택 이렇게 다양합니다',
 '표에 내용이 비어 있어, 어떤 주제를 다루는지 파악할 수 없습니다. 현재 제공된 표에는 열 이름이나 데이터가 없어 요약할 수 있는 주요 항목, 수치, 또는 컬럼 의미가 없습니다. 표의 실제 내용(컬럼명과 행 데이터)을 다시 보내주시면 2~4문장으로 검색용 요약을 작성해드리겠습니다.']

In [18]:
# testset 생성
from ragas.testset import TestsetGenerator
from ragas.llms import LangchainLLMWrapper
from ragas.embeddings import LangchainEmbeddingsWrapper
from langchain_openai import ChatOpenAI, OpenAIEmbeddings
#testsetgenerator 는 gpt-5 이후 버전은 사용할 수 없다. 
## Langchain의 모델과 Embedding 모델 -> ragas에서 사용할 수 있도록 변환(wrapping)
generator_llm = LangchainLLMWrapper(ChatOpenAI(model="gpt-4.1"))
generator_embeddings = LangchainEmbeddingsWrapper(OpenAIEmbeddings(model="text-embedding-3-large"))
generator = TestsetGenerator(
    llm=generator_llm,
    embedding_model=generator_embeddings,
    llm_context="""
- 사람들이 현역병 복지에 대해서 궁금해 할 만한 질문들을 생성한다.
- 데이터셋은 반드시 한국어로 작성한다.
- 데이터셋은 JSON 문법읋 지켜서 작성한다. 특히 구두점은 꼭 지켜야 한다.
- 생성된 내용이나 Document에 JSON문법에 맞지 않는 표현이 있으면 반드시 수정해서 처리한다.
""" 
# 질문/답변을 생성할 때 LLM에게 전달할 system Prompt를 설정
)

C:\Users\Playdata\AppData\Local\Temp\ipykernel_37040\3702810314.py:8: DeprecationWarning: LangchainLLMWrapper is deprecated and will be removed in a future version. Use llm_factory instead: from openai import OpenAI; from ragas.llms import llm_factory; llm = llm_factory('gpt-4o-mini', client=OpenAI(api_key='...'))
  generator_llm = LangchainLLMWrapper(ChatOpenAI(model="gpt-4.1"))
C:\Users\Playdata\AppData\Local\Temp\ipykernel_37040\3702810314.py:9: DeprecationWarning: LangchainEmbeddingsWrapper is deprecated and will be removed in a future version. Use the modern embedding providers instead: embedding_factory('openai', model='text-embedding-3-small', client=openai_client) or from ragas.embeddings import OpenAIEmbeddings, GoogleEmbeddings, HuggingFaceEmbeddings
  generator_embeddings = LangchainEmbeddingsWrapper(OpenAIEmbeddings(model="text-embedding-3-large"))

In [19]:
testset = generator.generate_with_chunks(
    docs, testset_size=10, # Context 내용 테스트셋 개수(질문 답변 개수)
)

Applying SummaryExtractor: 100%|██████████| 5/5 [00:07<00:00,  1.45s/it]
Applying CustomNodeFilter:   0%|          | 0/5 [00:00<?, ?it/s]Node defe1727-0887-4e4c-891b-de296d550c7b does not have a summary. Skipping filtering.
Node 3d3e72a2-fdd4-44ed-939b-933d60534d8d does not have a summary. Skipping filtering.
Node 23435d5b-6ca7-4542-bcd5-25b785cb5878 does not have a summary. Skipping filtering.
Node 995bf862-5888-4045-96bf-01686e80fd03 does not have a summary. Skipping filtering.
Node 03c99af3-7805-42bb-a503-19a3858cd15f does not have a summary. Skipping filtering.
Applying CustomNodeFilter: 100%|██████████| 5/5 [00:00<00:00, 489.18it/s]
Applying EmbeddingExtractor: 100%|██████████| 5/5 [00:01<00:00,  4.08it/s]
Applying ThemesExtractor: 100%|██████████| 5/5 [00:02<00:00,  2.40it/s]
Applying NERExtractor: 100%|██████████| 5/5 [00:02<00:00,  2.45it/s]
Applying CosineSimilarityBuilder: 100%|██████████| 1/1 [00:00<00:00, 142.45it/s]
Applying OverlapScoreBuilder: 100%|██████████| 1/1 [00:00<00:00, 512.88it/s]
Skipping multi_hop_abstract_query_synthesizer due to unexpected error: No relationships match the provided condition. Cannot form clusters.
Generating personas: 100%|██████████| 3/3 [00:02<00:00,  1.42it/s]
Generating Scenarios: 100%|██████████| 1/1 [00:13<00:00, 13.69s/it]
Generating Samples: 100%|██████████| 8/8 [00:02<00:00,  2.91it/s]

In [21]:
testset

Testset(samples=[TestsetSample(eval_sample=SingleTurnSample(user_input='국방일보 취업정보 어디서 볼수 있나요?', retrieved_contexts=None, reference_contexts=['01\nPart\n자\n기\n개\n발\n \n및\n \n전\n직\n지\n원\n \n분\n야\n67 \n03\nPart\n2026 초급간부 길라잡이\n-③-Ⅵ\n국민내일배움카드(고용노동부) \n-③-Ⅶ\n기 타\n 개 요 \n \x07전 생애에 걸친 직무수행능력 습득·향상을 위해 국민 스스로 직업능력개발훈련을 \n실시할 수 있도록 훈련비 등 지원\n* 단, 관련 법령에 따라 공무원, 군인 등 일부 대상 제외\n* \x07군인의 경우, 국민 평생 직업능력 개발법 시행령 제6조 및 군인사법 시행령 제60조의2에 \n따라 단기복무 전역예정자의 경우 예외적으로 지원\n 주요내용\n •(신청자격) 신청일 기준 ① 5년 미만의 기간동안 현역으로 복무하고, \n ② 전역예정일까지의 기간이 6개월 이하인 장교·준사관 또는 부사관\n •(지원내용) 계좌발급일로부터 5년간 300만원 이내 훈련비 지원*\n* 훈련과정 직종별 취업률, 소득수준 등에 따라 훈련비 일정비율(0~55%) 자비 부담\n •(신청절차)\n신청인\n⇨\n각 군\n⇨\n관할 고용센터\n⇨\n훈련생·훈련기관\n• \x07신청서 작성 후 \n소속부대 담당자\n에게 제출\n•신청자격 확인 \n•\x07관할 고용센터에\n 추천 공문 발송\n•\x07신청인이 방문하여 \n발급절차 진행\n•\x07개인별 훈련과정 신청 \n및 실시\n* \x07(참고) 군 전직 및 취업 지원 업무에 관한 훈령 제11조의2 및 별지 제8호 서식(훈련과정) \n한국기술교육대학교(직업능력심사평가원) 등의 심사결과에 따라 지방관서의 장이 인정·\n통지하는 훈련과정\n* \x07국민내일배움카드 사업내용 및 훈련과정 등 구체적인 내용은 고용24 홈페이지 (www.work24.\ngo.kr)에서 확인\n 취업정보 제공 \n •국방일보 취업정보 게재 (매주 화요일) : (http://kookbang.dema.mil.kr)\n •온라인(인터넷)을 통한 정보확인\n - \x07국방전직교육원(www.moti.or.kr) \n - 고용부 워크넷(www.work.go.kr)\n - 중소벤처기업진흥공단(www.kosmes.or.kr)\n - 국가보훈부 제대군인지원센터(www.vnet.go.kr)\n - 나라일터(www.gojobs.go.kr) 등\n국방부 일자리정책과 취업지원정책 | 900-6635\n담당부서'], retrieved_context_ids=None, reference_context_ids=None, response=None, multi_responses=None, reference='국방일보 취업정보는 매주 화요일 국방일보 홈페이지(http://kookbang.dema.mil.kr)에서 확인할 수 있습니다.', rubrics=None, persona_name='Job Seeker in Career Transition', query_style='MISSPELLED', query_length='MEDIUM'), synthesizer_name='single_hop_specific_query_synthesizer'), TestsetSample(eval_sample=SingleTurnSample(user_input='국방일보에서 국민내일배움카드 관련 취업정보를 어떻게 확인할 수 있나요?', retrieved_contexts=None, reference_contexts=['01\nPart\n자\n기\n개\n발\n \n및\n \n전\n직\n지\n원\n \n분\n야\n67 \n03\nPart\n2026 초급간부 길라잡이\n-③-Ⅵ\n국민내일배움카드(고용노동부) \n-③-Ⅶ\n기 타\n 개 요 \n \x07전 생애에 걸친 직무수행능력 습득·향상을 위해 국민 스스로 직업능력개발훈련을 \n실시할 수 있도록 훈련비 등 지원\n* 단, 관련 법령에 따라 공무원, 군인 등 일부 대상 제외\n* \x07군인의 경우, 국민 평생 직업능력 개발법 시행령 제6조 및 군인사법 시행령 제60조의2에 \n따라 단기복무 전역예정자의 경우 예외적으로 지원\n 주요내용\n •(신청자격) 신청일 기준 ① 5년 미만의 기간동안 현역으로 복무하고, \n ② 전역예정일까지의 기간이 6개월 이하인 장교·준사관 또는 부사관\n •(지원내용) 계좌발급일로부터 5년간 300만원 이내 훈련비 지원*\n* 훈련과정 직종별 취업률, 소득수준 등에 따라 훈련비 일정비율(0~55%) 자비 부담\n •(신청절차)\n신청인\n⇨\n각 군\n⇨\n관할 고용센터\n⇨\n훈련생·훈련기관\n• \x07신청서 작성 후 \n소속부대 담당자\n에게 제출\n•신청자격 확인 \n•\x07관할 고용센터에\n 추천 공문 발송\n•\x07신청인이 방문하여 \n발급절차 진행\n•\x07개인별 훈련과정 신청 \n및 실시\n* \x07(참고) 군 전직 및 취업 지원 업무에 관한 훈령 제11조의2 및 별지 제8호 서식(훈련과정) \n한국기술교육대학교(직업능력심사평가원) 등의 심사결과에 따라 지방관서의 장이 인정·\n통지하는 훈련과정\n* \x07국민내일배움카드 사업내용 및 훈련과정 등 구체적인 내용은 고용24 홈페이지 (www.work24.\ngo.kr)에서 확인\n 취업정보 제공 \n •국방일보 취업정보 게재 (매주 화요일) : (http://kookbang.dema.mil.kr)\n •온라인(인터넷)을 통한 정보확인\n - \x07국방전직교육원(www.moti.or.kr) \n - 고용부 워크넷(www.work.go.kr)\n - 중소벤처기업진흥공단(www.kosmes.or.kr)\n - 국가보훈부 제대군인지원센터(www.vnet.go.kr)\n - 나라일터(www.gojobs.go.kr) 등\n국방부 일자리정책과 취업지원정책 | 900-6635\n담당부서'], retrieved_context_ids=None, reference_context_ids=None, response=None, multi_responses=None, reference='국방일보에서는 매주 화요일 취업정보를 게재하며, 국민내일배움카드 관련 취업정보도 확인할 수 있습니다. 국방일보 취업정보는 http://kookbang.dema.mil.kr에서 온라인으로 확인할 수 있습니다.', rubrics=None, persona_name='Soon-to-be Discharged Service Member', query_style='WEB_SEARCH_LIKE', query_length='MEDIUM'), synthesizer_name='single_hop_specific_query_synthesizer'), TestsetSample(eval_sample=SingleTurnSample(user_input='장교 선발계획이 언제 어디에 올라오는지 알 수 있나요? 그리고 장교로 장기복무를 준비할 때 꼭 확인해야 하는 점이나 준비해야 할 사항이 뭔지 궁금합니다.', retrieved_contexts=None, reference_contexts=['이 표는 **각 군(육군·해군·공군·해병)의 장기복무(연장복무) 선발 안내**를 정리한 것으로, 장기복무 선발계획이 **홈페이지에 게시되는 시기**와 함께 선발 준비 시 확인해야 할 사항을 담고 있습니다. 컬럼은 문서 제목 아래에 각 군별 **장교/부사관 선발계획 탑재 시기**를 구분해 적고 있으며, 육군은 장교 전반기 전년도 12월·후반기 8월, 부사관 4월, 해군은 장교·부사관 전반기 1월, 부사관 후반기 6월, 공군은 장교 전반기 2월·부사관 전반기 1월, 해병은 장교 전반기 2월·후반기 9월, 부사관 전반기 3월·후반기 10월로 제시합니다. 또한 선발절차·추진일정·평가기준 등은 매년 최신화되며, 책임감 있는 임무수행과 대인관계, 관련 자격증 취득 같은 자기개발이 중요하다고 안내합니다. 마지막으로 장기복무 문의처와 각 군의 **선발 담당 부서/연'], retrieved_context_ids=None, reference_context_ids=None, response=None, multi_responses=None, reference='장교 선발계획은 각 군별로 홈페이지에 게시되는 시기가 다릅니다. 육군은 장교 전반기가 전년도 12월, 후반기가 8월에 게시되고, 해군은 장교 전반기가 1월, 공군과 해병은 장교 전반기가 2월에 게시됩니다. 장기복무를 준비할 때는 선발절차, 추진일정, 평가기준 등이 매년 최신화되므로 이를 확인해야 하며, 책임감 있는 임무수행, 대인관계, 관련 자격증 취득 같은 자기개발이 중요하다고 안내하고 있습니다.', rubrics=None, persona_name='Soon-to-be Discharged Service Member', query_style='MISSPELLED', query_length='LONG'), synthesizer_name='single_hop_specific_query_synthesizer'), TestsetSample(eval_sample=SingleTurnSample(user_input='부사관 장기복무 선발계획은 언제 확인할 수 있습니까?', retrieved_contexts=None, reference_contexts=['이 표는 **각 군(육군·해군·공군·해병)의 장기복무(연장복무) 선발 안내**를 정리한 것으로, 장기복무 선발계획이 **홈페이지에 게시되는 시기**와 함께 선발 준비 시 확인해야 할 사항을 담고 있습니다. 컬럼은 문서 제목 아래에 각 군별 **장교/부사관 선발계획 탑재 시기**를 구분해 적고 있으며, 육군은 장교 전반기 전년도 12월·후반기 8월, 부사관 4월, 해군은 장교·부사관 전반기 1월, 부사관 후반기 6월, 공군은 장교 전반기 2월·부사관 전반기 1월, 해병은 장교 전반기 2월·후반기 9월, 부사관 전반기 3월·후반기 10월로 제시합니다. 또한 선발절차·추진일정·평가기준 등은 매년 최신화되며, 책임감 있는 임무수행과 대인관계, 관련 자격증 취득 같은 자기개발이 중요하다고 안내합니다. 마지막으로 장기복무 문의처와 각 군의 **선발 담당 부서/연'], retrieved_context_ids=None, reference_context_ids=None, response=None, multi_responses=None, reference='부사관 장기복무 선발계획은 육군 4월, 해군 전반기 1월과 후반기 6월, 공군 전반기 1월, 해병 전반기 3월과 후반기 10월에 확인할 수 있습니다.', rubrics=None, persona_name='Military Career Progression Advisor', query_style='PERFECT_GRAMMAR', query_length='SHORT'), synthesizer_name='single_hop_specific_query_synthesizer'), TestsetSample(eval_sample=SingleTurnSample(user_input='③ 취업알선 단계에서 제공되는 맞춤형 취업 지원 서비스에는 어떤 내용이 포함되어 있습니까?', retrieved_contexts=None, reference_contexts=['이 표는 **취업알선 서비스의 구성 내용**을 정리한 것입니다. 주요 항목으로는 **채용정보 제공**, **직무/기업분석**, **그룹별 취업컨설팅**, **희망기업 알선**이 포함되어 있어, 구직자에게 맞춤형 취업 지원을 제공하는 내용을 나타냅니다. 컬럼의 제목인 **③ 취업알선**은 전체 프로그램의 세 번째 단계 또는 항목을 의미합니다.'], retrieved_context_ids=None, reference_context_ids=None, response=None, multi_responses=None, reference='③ 취업알선 단계에서 제공되는 맞춤형 취업 지원 서비스에는 채용정보 제공, 직무 및 기업분석, 그룹별 취업컨설팅, 희망기업 알선이 포함되어 있습니다. 이 서비스들은 구직자에게 맞춤형 취업 지원을 제공하는 것을 목적으로 합니다.', rubrics=None, persona_name='Job Seeker in Career Transition', query_style='PERFECT_GRAMMAR', query_length='LONG'), synthesizer_name='single_hop_specific_query_synthesizer'), TestsetSample(eval_sample=SingleTurnSample(user_input='취업알선 서비스에는 어떤 지원이 포함되어 있나요?', retrieved_contexts=None, reference_contexts=['이 표는 **취업알선 서비스의 구성 내용**을 정리한 것입니다. 주요 항목으로는 **채용정보 제공**, **직무/기업분석**, **그룹별 취업컨설팅**, **희망기업 알선**이 포함되어 있어, 구직자에게 맞춤형 취업 지원을 제공하는 내용을 나타냅니다. 컬럼의 제목인 **③ 취업알선**은 전체 프로그램의 세 번째 단계 또는 항목을 의미합니다.'], retrieved_context_ids=None, reference_context_ids=None, response=None, multi_responses=None, reference='취업알선 서비스에는 채용정보 제공, 직무/기업분석, 그룹별 취업컨설팅, 희망기업 알선이 포함되어 맞춤형 취업 지원을 제공합니다.', rubrics=None, persona_name='Job Seeker in Career Transition', query_style='WEB_SEARCH_LIKE', query_length='SHORT'), synthesizer_name='single_hop_specific_query_synthesizer'), TestsetSample(eval_sample=SingleTurnSample(user_input='국군재정관리단장 뭐 하는 사람인지 궁금해요, 사망보상금 받을 때 국군재정관리단장 역할이 뭐에요? 절차 복잡한지, 국군재정관리단장 어디서 나오고 무슨 일 하는지 자세히 알려주세요.', retrieved_contexts=None, reference_contexts=['Part 05 재해보상 분야\n58 2026 병 복지 길라잡이\n 재해보상금의 종류\n사망보상금, 장애보상금\n 사망보상금\n지급 대상\n • 군인이 공무 수행 중 사망한 경우, 그 유족(배우자, 자녀, 부모, 손자녀, \n조부모) 중 「민법」에 따른 상속 우선 순위자에게 지급\n지급 기준\n \n사망 구분\n보 상 기 준\n금 액\n전 사\n공무원 전체 기준소득월액 평균액× 60\n3억 4,260만원\n특수직무순직\n공무원 전체 기준소득월액 평균액× 45\n2억 5,695만원\n일반순직\n공무원 전체 기준소득월액 평균액× 24\n1억 3,704만원\n \n * ’25년 공무원 전체 기준소득월액 평균액 : 571만원 \n청구 및 지급절차\n \n순직여부 \n조사/결정\n➜\n청구서 제출\n➜\n접수\n➜\n확인/지급\n각 군 참모총장\n청구인\n국군재정관리단장/\n주소지 관할 \n지방보훈(지)청장\n국군재정관리단장\n • 각 군 전공사상심사위원회에서 순직여부 결정\n • 청구서 및 필요 구비서류를 준비하여 국군재정관리단 또는\n지방보훈(지)청에 제출\n • 국군재정관리단에서 순직여부 확인 및 지급 결정 후 청구인에게 통보\n • 국군재정관리단에서 급여액 산정 및 사망보상금 지급\n * 사망보상금 청구서는 군인연금 홈페이지에서 다운로드 가능(www.mps.mil.kr)\npart 05\n재해보상 분야\n▶▶▶ 병 복지혜택 이렇게 다양합니다'], retrieved_context_ids=None, reference_context_ids=None, response=None, multi_responses=None, reference='사망보상금 받을 때 국군재정관리단장은 중요한 역할을 해요. 순직여부가 각 군 전공사상심사위원회에서 결정되면, 청구서와 필요 서류를 국군재정관리단이나 지방보훈(지)청에 제출해야 해요. 국군재정관리단장은 순직여부를 확인하고 지급 결정을 한 다음, 청구인에게 통보해요. 그리고 급여액 산정과 사망보상금 지급도 국군재정관리단장이 담당해요. 즉, 국군재정관리단장은 사망보상금 지급 절차에서 확인, 결정, 통보, 지급까지 여러 단계에 관여하는 중요한 역할을 해요.', rubrics=None, persona_name='Job Seeker in Career Transition', query_style='POOR_GRAMMAR', query_length='LONG'), synthesizer_name='single_hop_specific_query_synthesizer'), TestsetSample(eval_sample=SingleTurnSample(user_input='각 군 전공사상심사위원회는 어떤 역할을 하나요?', retrieved_contexts=None, reference_contexts=['Part 05 재해보상 분야\n58 2026 병 복지 길라잡이\n 재해보상금의 종류\n사망보상금, 장애보상금\n 사망보상금\n지급 대상\n • 군인이 공무 수행 중 사망한 경우, 그 유족(배우자, 자녀, 부모, 손자녀, \n조부모) 중 「민법」에 따른 상속 우선 순위자에게 지급\n지급 기준\n \n사망 구분\n보 상 기 준\n금 액\n전 사\n공무원 전체 기준소득월액 평균액× 60\n3억 4,260만원\n특수직무순직\n공무원 전체 기준소득월액 평균액× 45\n2억 5,695만원\n일반순직\n공무원 전체 기준소득월액 평균액× 24\n1억 3,704만원\n \n * ’25년 공무원 전체 기준소득월액 평균액 : 571만원 \n청구 및 지급절차\n \n순직여부 \n조사/결정\n➜\n청구서 제출\n➜\n접수\n➜\n확인/지급\n각 군 참모총장\n청구인\n국군재정관리단장/\n주소지 관할 \n지방보훈(지)청장\n국군재정관리단장\n • 각 군 전공사상심사위원회에서 순직여부 결정\n • 청구서 및 필요 구비서류를 준비하여 국군재정관리단 또는\n지방보훈(지)청에 제출\n • 국군재정관리단에서 순직여부 확인 및 지급 결정 후 청구인에게 통보\n • 국군재정관리단에서 급여액 산정 및 사망보상금 지급\n * 사망보상금 청구서는 군인연금 홈페이지에서 다운로드 가능(www.mps.mil.kr)\npart 05\n재해보상 분야\n▶▶▶ 병 복지혜택 이렇게 다양합니다'], retrieved_context_ids=None, reference_context_ids=None, response=None, multi_responses=None, reference='각 군 전공사상심사위원회에서는 순직여부를 결정합니다.', rubrics=None, persona_name='Military Career Progression Advisor', query_style='PERFECT_GRAMMAR', query_length='SHORT'), synthesizer_name='single_hop_specific_query_synthesizer')])

In [22]:
sample1 = testset.samples[0].eval_sample
print("사용자질문:", sample1.user_input)
print("Context:", sample1.reference_contexts)
print("생성된 답변(정답):", sample1.reference)
print("평가대상 RAG의 답변:", sample1.response)
print("평가대상 RAG가 검색한 Context:", sample1.retrieved_contexts)

사용자질문: 국방일보 취업정보 어디서 볼수 있나요?
Context: ['01\nPart\n자\n기\n개\n발\n \n및\n \n전\n직\n지\n원\n \n분\n야\n67 \n03\nPart\n2026 초급간부 길라잡이\n-③-Ⅵ\n국민내일배움카드(고용노동부) \n-③-Ⅶ\n기 타\n 개 요 \n \x07전 생애에 걸친 직무수행능력 습득·향상을 위해 국민 스스로 직업능력개발훈련을 \n실시할 수 있도록 훈련비 등 지원\n* 단, 관련 법령에 따라 공무원, 군인 등 일부 대상 제외\n* \x07군인의 경우, 국민 평생 직업능력 개발법 시행령 제6조 및 군인사법 시행령 제60조의2에 \n따라 단기복무 전역예정자의 경우 예외적으로 지원\n 주요내용\n •(신청자격) 신청일 기준 ① 5년 미만의 기간동안 현역으로 복무하고, \n ② 전역예정일까지의 기간이 6개월 이하인 장교·준사관 또는 부사관\n •(지원내용) 계좌발급일로부터 5년간 300만원 이내 훈련비 지원*\n* 훈련과정 직종별 취업률, 소득수준 등에 따라 훈련비 일정비율(0~55%) 자비 부담\n •(신청절차)\n신청인\n⇨\n각 군\n⇨\n관할 고용센터\n⇨\n훈련생·훈련기관\n• \x07신청서 작성 후 \n소속부대 담당자\n에게 제출\n•신청자격 확인 \n•\x07관할 고용센터에\n 추천 공문 발송\n•\x07신청인이 방문하여 \n발급절차 진행\n•\x07개인별 훈련과정 신청 \n및 실시\n* \x07(참고) 군 전직 및 취업 지원 업무에 관한 훈령 제11조의2 및 별지 제8호 서식(훈련과정) \n한국기술교육대학교(직업능력심사평가원) 등의 심사결과에 따라 지방관서의 장이 인정·\n통지하는 훈련과정\n* \x07국민내일배움카드 사업내용 및 훈련과정 등 구체적인 내용은 고용24 홈페이지 (www.work24.\ngo.kr)에서 확인\n 취업정보 제공 \n •국방일보 취업정보 게재 (매주 화요일) : (http://kookbang.dema.mil.kr)\n •온라인(인터넷)을 통한 정보확인\n - \x07국방전직교육원(www.moti.or.kr) \n - 고용부 워크넷(www.work.go.kr)\n - 중소벤처기업진흥공단(www.kosmes.or.kr)\n - 국가보훈부 제대군인지원센터(www.vnet.go.kr)\n - 나라일터(www.gojobs.go.kr) 등\n국방부 일자리정책과 취업지원정책 | 900-6635\n담당부서']
생성된 답변(정답): 국방일보 취업정보는 매주 화요일 국방일보 홈페이지(http://kookbang.dema.mil.kr)에서 확인할 수 있습니다.
평가대상 RAG의 답변: None
평가대상 RAG가 검색한 Context: None

In [23]:
# 생성된 Testset을 Pandas DataFrame으로 변환
eval_df = testset.to_pandas()

In [24]:
eval_df.shape

(8, 7)

In [25]:
eval_df

,user_input,reference_contexts,reference,persona_name,query_style,query_length,synthesizer_name
0,국방일보 취업정보 어디서 볼수 있나요?,[01\nPart\n자\n기\n개\n발\n \n및\n \n전\n직\n지\n원\n \...,국방일보 취업정보는 매주 화요일 국방일보 홈페이지(http://kookbang.de...,Job Seeker in Career Transition,MISSPELLED,MEDIUM,single_hop_specific_query_synthesizer
1,국방일보에서 국민내일배움카드 관련 취업정보를 어떻게 확인할 수 있나요?,[01\nPart\n자\n기\n개\n발\n \n및\n \n전\n직\n지\n원\n \...,"국방일보에서는 매주 화요일 취업정보를 게재하며, 국민내일배움카드 관련 취업정보도 확...",Soon-to-be Discharged Service Member,WEB_SEARCH_LIKE,MEDIUM,single_hop_specific_query_synthesizer
2,장교 선발계획이 언제 어디에 올라오는지 알 수 있나요? 그리고 장교로 장기복무를 준...,[이 표는 **각 군(육군·해군·공군·해병)의 장기복무(연장복무) 선발 안내**를 ...,장교 선발계획은 각 군별로 홈페이지에 게시되는 시기가 다릅니다. 육군은 장교 전반기...,Soon-to-be Discharged Service Member,MISSPELLED,LONG,single_hop_specific_query_synthesizer
3,부사관 장기복무 선발계획은 언제 확인할 수 있습니까?,[이 표는 **각 군(육군·해군·공군·해병)의 장기복무(연장복무) 선발 안내**를 ...,"부사관 장기복무 선발계획은 육군 4월, 해군 전반기 1월과 후반기 6월, 공군 전반...",Military Career Progression Advisor,PERFECT_GRAMMAR,SHORT,single_hop_specific_query_synthesizer
4,③ 취업알선 단계에서 제공되는 맞춤형 취업 지원 서비스에는 어떤 내용이 포함되어 있...,[이 표는 **취업알선 서비스의 구성 내용**을 정리한 것입니다. 주요 항목으로는 ...,"③ 취업알선 단계에서 제공되는 맞춤형 취업 지원 서비스에는 채용정보 제공, 직무 및...",Job Seeker in Career Transition,PERFECT_GRAMMAR,LONG,single_hop_specific_query_synthesizer
5,취업알선 서비스에는 어떤 지원이 포함되어 있나요?,[이 표는 **취업알선 서비스의 구성 내용**을 정리한 것입니다. 주요 항목으로는 ...,"취업알선 서비스에는 채용정보 제공, 직무/기업분석, 그룹별 취업컨설팅, 희망기업 알...",Job Seeker in Career Transition,WEB_SEARCH_LIKE,SHORT,single_hop_specific_query_synthesizer
6,"국군재정관리단장 뭐 하는 사람인지 궁금해요, 사망보상금 받을 때 국군재정관리단장 역...",[Part 05 재해보상 분야\n58 2026 병 복지 길라잡이\n 재해보상금의 종...,사망보상금 받을 때 국군재정관리단장은 중요한 역할을 해요. 순직여부가 각 군 전공사...,Job Seeker in Career Transition,POOR_GRAMMAR,LONG,single_hop_specific_query_synthesizer
7,각 군 전공사상심사위원회는 어떤 역할을 하나요?,[Part 05 재해보상 분야\n58 2026 병 복지 길라잡이\n 재해보상금의 종...,각 군 전공사상심사위원회에서는 순직여부를 결정합니다.,Military Career Progression Advisor,PERFECT_GRAMMAR,SHORT,single_hop_specific_query_synthesizer

In [26]:
from tools import search_guidance_knowledge_base
row_idx = 0
q = eval_df.loc[row_idx, 'user_input']
# resp = search_guidance_knowledge_base.invoke(q)
resp = chain.invoke(q)

In [27]:
# resp
resp['response']

'국방일보 취업정보는 매주 화요일에 국방일보에서 확인할 수 있으며, 웹사이트는 다음과 같습니다.\n\n- http://kookbang.dema.mil.kr\n\n'

In [28]:
# resp
resp['retrieved_context']

['01\nPart\n자\n기\n개\n발\n \n및\n \n전\n직\n지\n원\n \n분\n야\n67 \n03\nPart\n2026 초급간부 길라잡이\n-③-Ⅵ\n국민내일배움카드(고용노동부) \n-③-Ⅶ\n기 타\n 개 요 \n \x07전 생애에 걸친 직무수행능력 습득·향상을 위해 국민 스스로 직업능력개발훈련을 \n실시할 수 있도록 훈련비 등 지원\n* 단, 관련 법령에 따라 공무원, 군인 등 일부 대상 제외\n* \x07군인의 경우, 국민 평생 직업능력 개발법 시행령 제6조 및 군인사법 시행령 제60조의2에 \n따라 단기복무 전역예정자의 경우 예외적으로 지원\n 주요내용\n •(신청자격) 신청일 기준 ① 5년 미만의 기간동안 현역으로 복무하고, \n ② 전역예정일까지의 기간이 6개월 이하인 장교·준사관 또는 부사관\n •(지원내용) 계좌발급일로부터 5년간 300만원 이내 훈련비 지원*\n* 훈련과정 직종별 취업률, 소득수준 등에 따라 훈련비 일정비율(0~55%) 자비 부담\n •(신청절차)\n신청인\n⇨\n각 군\n⇨\n관할 고용센터\n⇨\n훈련생·훈련기관\n• \x07신청서 작성 후 \n소속부대 담당자\n에게 제출\n•신청자격 확인 \n•\x07관할 고용센터에\n 추천 공문 발송\n•\x07신청인이 방문하여 \n발급절차 진행\n•\x07개인별 훈련과정 신청 \n및 실시\n* \x07(참고) 군 전직 및 취업 지원 업무에 관한 훈령 제11조의2 및 별지 제8호 서식(훈련과정) \n한국기술교육대학교(직업능력심사평가원) 등의 심사결과에 따라 지방관서의 장이 인정·\n통지하는 훈련과정\n* \x07국민내일배움카드 사업내용 및 훈련과정 등 구체적인 내용은 고용24 홈페이지 (www.work24.\ngo.kr)에서 확인\n 취업정보 제공 \n •국방일보 취업정보 게재 (매주 화요일) : (http://kookbang.dema.mil.kr)\n •온라인(인터넷)을 통한 정보확인\n - \x07국방전직교육원(www.moti.or.kr) \n - 고용부 워크넷(www.work.go.kr)\n - 중소벤처기업진흥공단(www.kosmes.or.kr)\n - 국가보훈부 제대군인지원센터(www.vnet.go.kr)\n - 나라일터(www.gojobs.go.kr) 등\n국방부 일자리정책과 취업지원정책 | 900-6635\n담당부서',
 'Part 06 사회적응 지원 분야\n68 2026 병 복지 길라잡이\n • 국방일보 취업정보 게재(매주 화요일) : (http://kookbang.dema.mill.kr/)\n • 온라인(인터넷)을 통한 정보확인\n - 국방전직교육원(www.moti.or.kr) \n - 중소벤처기업진흥공단(www.kosmes.or.kr)\n - 창업진흥원(www.kised.or.kr) \n - 국가보훈부 제대군인지원센터(www.vnet.go.kr)\n - 나라일터(www.gojobs.go.kr) 등\n☎ 문의 : 국방전직교육원(1588-9402) 또는 사·여단 취·창업 담당자\n취업맞춤특기병 특화 프로그램운영\n • 편성 : 연 4회, 2일 과정, 소집교육 / 국방전직교육원, 폴리텍대학\n \n* 연간 및 분기별 교육계획은 국방전직교육원 홈페이지(www.moti.or.kr) 참조\n • 취업맞춤특기병 취업역량 향상 및 체험중심 취업지원 프로그램\n구 분\n내 용 \n구 분\n내 용\n1일차\n(6H)\n기술직무 이해 및 체험\n - 체험 기술분야 이해\n - 제조 전공정 체험·실습\n2일차\n(3H)\n1:1상담 취업컨설팅\n - 개인별 강점분석\n - 진로·취업 로드맵\n☎ 문의 : 국방전직교육원(1588-9402) 또는 사·여단 취·창업 담당자',
 '64 \n2026 초급간부 길라잡이\n-③-Ⅳ\n국군장병 취업박람회(Military Job Fair)\n 개 요 \n \x07초급간부 복무여건 개선을 위하여 정책적 취업 지원 노력의 일환으로서, \n국가에 헌신한 장병의 취업역량 강화 및 우수기업 취업 등 안정적 \n사회정착을 위하여 매년 국방부 주관, 국방전직교육원 주최의 국군장병 \n취업박람회를 개최함.\n 주요내용\n •\x07참여대상 : 국가와 군을 위해 헌신한 국군장병 중 취업지원이 우선으로 \n필요한 장병은 누구나 참여할 수 있음\n •참가규모 : 장병 약 1~2만명, 구인희망기업 약 200여 개 社\n •\x07부스(Booth) 구성 : 기업 취업 상담, 취업컨설팅, 현직자 멘토링, 현장면접, \n채용설명회, AI 역량검사, VR 진로·취업체험 등\n구 분\n주 요 내 용\n국방부 \n통합부스\n•국군장병 취업지원사업 소개, 참가장병 확인\n각 군 \n모집관\n•육·해·공·해병·특전사, 병무청(맞춤형 특기병)\n공공기관\n홍보관\n•\x07서울특별시, 국민체육진흥공단, 대한무역투자진흥공사, 한국고용\n정보원, 한국의료기기안전정보원, 한국대드론산업협회 등\n기업\n채용관\n•\x07업종별(건설·토목/경호·경비/방산/서비스업/IT/제조업/운수 창고업 등) \n테마관 구성\n•기업 인사담당자와 구직자 간 면접 및 채용 상담\n미래유망직종\n체험관\n•\x07자율주행 로봇 체험, AI 딥페이크 체험, 인공지능 자율주행 체험, \n안전관리 메타버스 체험, 패키징 와이어본더 체험, 반도체 증착 및 \n공정 체험 등\n세미나\nA관\n개막식•개막식 행사 진행\n채용\n설명회\n•미래유망 직종에 관한 채용설명회 및 Q&A 진행\n•채용 트렌드를 알아보고, 분야별 성공취업 전략 제시',
 'Part 06 사회적응 지원 분야\n66 2026 병 복지 길라잡이\n취업 및 창업 지원\n온라인 취업 및 진로교육, 자기개발 및 취·창업지원 사업 안내\n • 취업 및 진로교육(사이버아카데미) : 국방전직교육원 홈페이지 (www.moti.or.kr) \n - 전역 후 제2의 인생 설계, 구직역량 강화\n - 대상 : 군 복무 전 장병, 온라인 상시학습 가능\n • 직업 심리검사 : 고용24(www.work24.go.kr) / 무료\n - 직업선호도·진로준비도·구직준비도 검사 등 \n국방부(국방전직교육원) 취업지원 교육 및 일자리 지원 사업 현황\n사업명\n대상\n내용\n사이버아카데미\n군 복무 중인 全 장병\n◦전직준비 및 생애설계 역량 강화를 위한 \n사이버교육\n국군장병\n취업박람회\n군 복무 중인 全 장병\n◦취업정보제공, 맞춤형 컨설팅, 구인기업 \n현장면접 등\n청년장병 뉴스타트(Ⅰ)\n(취업역량 기본과정)\n청년장병\n◦취업준비 분야별 맞춤형 취업역량 \n집중교육(2박3일 소집교육)\n청년장병 뉴스타트(Ⅱ)\n(취업준비 심화과정)\n청년장병\n◦기업별 맞춤형교육 및 개인별 취업매칭 \n및 컨설팅(2박3일 소집교육)\n청년장병 뉴스타트(Ⅲ)\n(채용 설명회)\n청년장병\n◦기업, 공직, 업종별 취ㆍ창업 \n설명회 개최\n창업인식개선교육\n창업 관심 장병\n◦창업 인식개선 및 예비참여 준비과정 등\n창업멘토링\n창업희망팀 및\n국방창업경진대회진출팀\n◦전문 멘토링 집중 지원\n국방창업경진대회\n(군-국방부)\n창업 관심\n전역예정장병\n◦장병들의 창업 아이디어 발굴 및 육성, \n범부처 창업경진대회와 연계·추진\n취업컨설팅\n국방전직교육원\n구직등록 全 장병\n◦맞춤형 1:1 상담 지원\n ☞ 취업을 희망하는 인원은 구직등록 후 업무담당자에게 문의 바랍니다.\n * 구직등록: 국방전직교육원 홈페이지(www.moti.or.kr) → 회원가입 → 마이페이지\npart 06\n사회적응 지원 분야\n▶▶▶ 병 복지혜택 이렇게 다양합니다',
 '2026 병 복지 길라잡이 67\n고용노동부 취업 안내 \n • 주관：전국 102개 고용(복지+)센터(www.workplus.go.kr)\n • 이용대상：전 국민, 전역 후 활용 가능\n • 이용절차\n - 고용(복지+)센터 방문 또는 고용24(www.work24.go.kr)에서 구직 신청\n - 구직자에게 일자리 정보 및 취업특강 등 취업지원 프로그램 제공\n - 국민취업지원제도* 등을 통해 취약계층 대상 통합적인 고용서비스\n (취업상담-직업훈련-취업알선) 제공\n \n* 소득, 재산 등 지원요건 해당 시 생계지원(구직촉진수당) \n < 고용(복지+)센터 구직자 취업지원 서비스 흐름도 > \n<고용24 구직신청>\n- 고용24에서 개인회원으\n로 가입하여 직접 구직\n신청\n- 또는 고용(복지+)센터\n에 방문하여 구직 신청\n서 제출\n<직업상담 및 취업알선>\n- 고용(복지+)센터: 적합한 진\n로선택을 위한 직업상담을 \n실시하고, 그 능력과 취업 \n희망조건에 적합한 일자리\n를 소개하거나 구직기술 향\n상 및 고용정보 제공을 위한 \n취업지원프로그램 등 운영 \n- 구직자는 고용24에서 일자\n리정보를 검색하여 직접 입\n사지원 가능\n<취업 및 결과 통보>\n- 구인, 구직자는 고용24\n으로 채용결과를 직접 \n입력하거나 고용(복지+)\n센터에 채용결과를 통보 \n- 미취업 시 고용(복지+)센\n터에 취업지원서비스 등\n을 다시 신청\n - 훈련비 지원을 위한 국민내일배움카드(직업능력개발계좌) 발급 \n \n* 고용24(www.work24.go.kr)에서 신청 가능(실업자는 먼저 구직 신청을 완료해야 가능)\n \n* 추천 : 국방부, 국가보훈부 / 운영 : 고용노동부\n • 문의처 \n - 고용노동부 고객상담센터 (국번 없이 1350) \n \n* 평일 오전 9시~ 오후 6시 상담(주말 및 공휴일 휴무)\n - 고용24(www.work24.go.kr) 홈페이지']

In [49]:
# 모든 testset의 데이터데 대한 llm 응답과 retriever의 검색 겷과를 추가
response_list = []
retrieved_context_list = []

for user_input in eval_df['user_input']:
    resp = chain.invoke(user_input)
    response_list.append(resp["response"])
    retrieved_context_list.append(resp["retrieved_context"])

In [38]:
print(len(response_list), len(retrieved_context_list))

8 8

In [39]:
response_list

['국방일보 취업정보는 **국방일보 홈페이지**에서 볼 수 있습니다.  \n경로는 다음과 같습니다.\n\n- **국방일보 취업정보 게재(매주 화요일)**: http://kookbang.dema.mil.kr\n\n',
 '국방일보의 취업정보는 **매주 화요일 국방일보에 게재**되며,  \n해당 정보는 **국방일보 홈페이지**에서 확인할 수 있습니다:\n\n- **http://kookbang.dema.mil.kr**\n\n또한 관련 취업정보는 온라인으로 다음 사이트에서도 확인 가능합니다:\n- 국방전직교육원: **www.moti.or.kr**\n- 고용부 워크넷: **www.work.go.kr**\n- 중소벤처기업진흥공단: **www.kosmes.or.kr**\n- 국가보훈부 제대군인지원센터: **www.vnet.go.kr**\n- 나라일터: **www.gojobs.go.kr**',
 '네, Context에 따르면 장교 선발계획은 **각 군 홈페이지**에 올라오며, 탑재 시기는 다음과 같습니다.\n\n- **육군**: 전반기 **전년도 12월**, 후반기 **8월**\n- **해군**: 전반기 **1월**\n- **공군**: 전반기 **2월**\n- **해병**: 전반기 **2월**, 후반기 **9월**\n\n또한 공군은 **선발결과만 홈페이지에 게시**되고, **계획은 공문으로 전파**된다고 되어 있습니다.\n\n장교로 장기복무를 준비할 때 꼭 확인해야 할 점은 다음과 같습니다.\n\n- **당해 연도 각 군별 장기복무 선발계획**\n- **선발절차**\n- **추진일정**\n- **선발방법 및 평가기준**\n- **매년 최신화되는 세부 평가요소**\n\n준비해야 할 사항으로는 다음이 안내되어 있습니다.\n\n- **본인 소관 업무를 책임감 있게 수행하기**\n- **상급자·하급자·동료와 원만한 관계 유지하기**\n- **해당 특기/분야에서 인정하는 자격증 등 자기개발 활동 하기**\n\n정보가 부족해 답을 할 수없습니다.',
 '부사관 장기복무 선발계획은 각 군별로 홈페이지에 게시되는 시기가 다릅니다.\n\n- **육군**: 4월  \n- **해군**: 전반기 1월 / 후반기 6월  \n- **공군**: 전반기 1월  \n- **해병대**: 전반기 3월 / 후반기 10월  \n\n또한 공군은 **선발결과만 홈페이지에 게시**되고, **선발계획은 공문으로 전파**됩니다.',
 '③ 취업알선 단계에서 제공되는 맞춤형 취업 지원 서비스에는 **채용정보 제공, 직무/기업분석, 그룹별 취업컨설팅, 희망기업 알선**이 포함됩니다.',
 '취업알선 서비스에는 **채용정보 제공, 직무/기업분석, 그룹별 취업컨설팅, 희망기업 알선**이 포함됩니다.',
 '제공된 context에 따르면, **사망보상금 청구·지급 절차에서 국군재정관리단장**은 다음 역할을 합니다.\n\n### 사망보상금 관련 역할\n- **유족이 청구서를 제출하면 접수하는 역할**을 합니다.\n- **순직 여부를 확인**하고 **지급 결정을 내린 뒤 청구인에게 통보**합니다.\n- 이후 **급여액을 산정하고 사망보상금을 지급**합니다.\n\n### 절차에서의 위치\n사망보상금 청구 및 지급 절차는 context상 다음과 같습니다.\n\n1. **각 군 전공사상심사위원회에서 순직 여부 결정**\n2. **유족이 청구서 제출**\n   - 국군재정관리단 또는 주소지 관할 지방보훈(지)청에 제출\n3. **국군재정관리단장 접수**\n4. **순직 여부 확인 및 지급 결정 후 청구인에게 통보**\n5. **급여액 산정 및 사망보상금 지급**\n\n### 국군재정관리단장이 “어디서 나오나”\ncontext에는 **국군재정관리단장**이 **사망보상금 청구·지급을 담당하는 기관의 장**으로 등장합니다.  \n다만, **국군재정관리단장이 어떤 조직인지, 어떤 사람인지에 대한 상세 설명은 context에 없습니다.**\n\n### 절차가 복잡한지\ncontext에는 절차가 **순직 여부 심사 → 청구 → 접수/확인 → 지급** 순으로 안내되어 있지만,  \n**복잡한지에 대한 평가는 나와 있지 않습니다.**\n\n정보가 부족해 답을 할 수없습니다.',
 '정보가 부족해 답을 할 수없습니다.']

In [40]:
retrieved_context_list

[['01\nPart\n자\n기\n개\n발\n \n및\n \n전\n직\n지\n원\n \n분\n야\n67 \n03\nPart\n2026 초급간부 길라잡이\n-③-Ⅵ\n국민내일배움카드(고용노동부) \n-③-Ⅶ\n기 타\n 개 요 \n \x07전 생애에 걸친 직무수행능력 습득·향상을 위해 국민 스스로 직업능력개발훈련을 \n실시할 수 있도록 훈련비 등 지원\n* 단, 관련 법령에 따라 공무원, 군인 등 일부 대상 제외\n* \x07군인의 경우, 국민 평생 직업능력 개발법 시행령 제6조 및 군인사법 시행령 제60조의2에 \n따라 단기복무 전역예정자의 경우 예외적으로 지원\n 주요내용\n •(신청자격) 신청일 기준 ① 5년 미만의 기간동안 현역으로 복무하고, \n ② 전역예정일까지의 기간이 6개월 이하인 장교·준사관 또는 부사관\n •(지원내용) 계좌발급일로부터 5년간 300만원 이내 훈련비 지원*\n* 훈련과정 직종별 취업률, 소득수준 등에 따라 훈련비 일정비율(0~55%) 자비 부담\n •(신청절차)\n신청인\n⇨\n각 군\n⇨\n관할 고용센터\n⇨\n훈련생·훈련기관\n• \x07신청서 작성 후 \n소속부대 담당자\n에게 제출\n•신청자격 확인 \n•\x07관할 고용센터에\n 추천 공문 발송\n•\x07신청인이 방문하여 \n발급절차 진행\n•\x07개인별 훈련과정 신청 \n및 실시\n* \x07(참고) 군 전직 및 취업 지원 업무에 관한 훈령 제11조의2 및 별지 제8호 서식(훈련과정) \n한국기술교육대학교(직업능력심사평가원) 등의 심사결과에 따라 지방관서의 장이 인정·\n통지하는 훈련과정\n* \x07국민내일배움카드 사업내용 및 훈련과정 등 구체적인 내용은 고용24 홈페이지 (www.work24.\ngo.kr)에서 확인\n 취업정보 제공 \n •국방일보 취업정보 게재 (매주 화요일) : (http://kookbang.dema.mil.kr)\n •온라인(인터넷)을 통한 정보확인\n - \x07국방전직교육원(www.moti.or.kr) \n - 고용부 워크넷(www.work.go.kr)\n - 중소벤처기업진흥공단(www.kosmes.or.kr)\n - 국가보훈부 제대군인지원센터(www.vnet.go.kr)\n - 나라일터(www.gojobs.go.kr) 등\n국방부 일자리정책과 취업지원정책 | 900-6635\n담당부서',
  'Part 06 사회적응 지원 분야\n68 2026 병 복지 길라잡이\n • 국방일보 취업정보 게재(매주 화요일) : (http://kookbang.dema.mill.kr/)\n • 온라인(인터넷)을 통한 정보확인\n - 국방전직교육원(www.moti.or.kr) \n - 중소벤처기업진흥공단(www.kosmes.or.kr)\n - 창업진흥원(www.kised.or.kr) \n - 국가보훈부 제대군인지원센터(www.vnet.go.kr)\n - 나라일터(www.gojobs.go.kr) 등\n☎ 문의 : 국방전직교육원(1588-9402) 또는 사·여단 취·창업 담당자\n취업맞춤특기병 특화 프로그램운영\n • 편성 : 연 4회, 2일 과정, 소집교육 / 국방전직교육원, 폴리텍대학\n \n* 연간 및 분기별 교육계획은 국방전직교육원 홈페이지(www.moti.or.kr) 참조\n • 취업맞춤특기병 취업역량 향상 및 체험중심 취업지원 프로그램\n구 분\n내 용 \n구 분\n내 용\n1일차\n(6H)\n기술직무 이해 및 체험\n - 체험 기술분야 이해\n - 제조 전공정 체험·실습\n2일차\n(3H)\n1:1상담 취업컨설팅\n - 개인별 강점분석\n - 진로·취업 로드맵\n☎ 문의 : 국방전직교육원(1588-9402) 또는 사·여단 취·창업 담당자',
  '64 \n2026 초급간부 길라잡이\n-③-Ⅳ\n국군장병 취업박람회(Military Job Fair)\n 개 요 \n \x07초급간부 복무여건 개선을 위하여 정책적 취업 지원 노력의 일환으로서, \n국가에 헌신한 장병의 취업역량 강화 및 우수기업 취업 등 안정적 \n사회정착을 위하여 매년 국방부 주관, 국방전직교육원 주최의 국군장병 \n취업박람회를 개최함.\n 주요내용\n •\x07참여대상 : 국가와 군을 위해 헌신한 국군장병 중 취업지원이 우선으로 \n필요한 장병은 누구나 참여할 수 있음\n •참가규모 : 장병 약 1~2만명, 구인희망기업 약 200여 개 社\n •\x07부스(Booth) 구성 : 기업 취업 상담, 취업컨설팅, 현직자 멘토링, 현장면접, \n채용설명회, AI 역량검사, VR 진로·취업체험 등\n구 분\n주 요 내 용\n국방부 \n통합부스\n•국군장병 취업지원사업 소개, 참가장병 확인\n각 군 \n모집관\n•육·해·공·해병·특전사, 병무청(맞춤형 특기병)\n공공기관\n홍보관\n•\x07서울특별시, 국민체육진흥공단, 대한무역투자진흥공사, 한국고용\n정보원, 한국의료기기안전정보원, 한국대드론산업협회 등\n기업\n채용관\n•\x07업종별(건설·토목/경호·경비/방산/서비스업/IT/제조업/운수 창고업 등) \n테마관 구성\n•기업 인사담당자와 구직자 간 면접 및 채용 상담\n미래유망직종\n체험관\n•\x07자율주행 로봇 체험, AI 딥페이크 체험, 인공지능 자율주행 체험, \n안전관리 메타버스 체험, 패키징 와이어본더 체험, 반도체 증착 및 \n공정 체험 등\n세미나\nA관\n개막식•개막식 행사 진행\n채용\n설명회\n•미래유망 직종에 관한 채용설명회 및 Q&A 진행\n•채용 트렌드를 알아보고, 분야별 성공취업 전략 제시',
  'Part 06 사회적응 지원 분야\n66 2026 병 복지 길라잡이\n취업 및 창업 지원\n온라인 취업 및 진로교육, 자기개발 및 취·창업지원 사업 안내\n • 취업 및 진로교육(사이버아카데미) : 국방전직교육원 홈페이지 (www.moti.or.kr) \n - 전역 후 제2의 인생 설계, 구직역량 강화\n - 대상 : 군 복무 전 장병, 온라인 상시학습 가능\n • 직업 심리검사 : 고용24(www.work24.go.kr) / 무료\n - 직업선호도·진로준비도·구직준비도 검사 등 \n국방부(국방전직교육원) 취업지원 교육 및 일자리 지원 사업 현황\n사업명\n대상\n내용\n사이버아카데미\n군 복무 중인 全 장병\n◦전직준비 및 생애설계 역량 강화를 위한 \n사이버교육\n국군장병\n취업박람회\n군 복무 중인 全 장병\n◦취업정보제공, 맞춤형 컨설팅, 구인기업 \n현장면접 등\n청년장병 뉴스타트(Ⅰ)\n(취업역량 기본과정)\n청년장병\n◦취업준비 분야별 맞춤형 취업역량 \n집중교육(2박3일 소집교육)\n청년장병 뉴스타트(Ⅱ)\n(취업준비 심화과정)\n청년장병\n◦기업별 맞춤형교육 및 개인별 취업매칭 \n및 컨설팅(2박3일 소집교육)\n청년장병 뉴스타트(Ⅲ)\n(채용 설명회)\n청년장병\n◦기업, 공직, 업종별 취ㆍ창업 \n설명회 개최\n창업인식개선교육\n창업 관심 장병\n◦창업 인식개선 및 예비참여 준비과정 등\n창업멘토링\n창업희망팀 및\n국방창업경진대회진출팀\n◦전문 멘토링 집중 지원\n국방창업경진대회\n(군-국방부)\n창업 관심\n전역예정장병\n◦장병들의 창업 아이디어 발굴 및 육성, \n범부처 창업경진대회와 연계·추진\n취업컨설팅\n국방전직교육원\n구직등록 全 장병\n◦맞춤형 1:1 상담 지원\n ☞ 취업을 희망하는 인원은 구직등록 후 업무담당자에게 문의 바랍니다.\n * 구직등록: 국방전직교육원 홈페이지(www.moti.or.kr) → 회원가입 → 마이페이지\npart 06\n사회적응 지원 분야\n▶▶▶ 병 복지혜택 이렇게 다양합니다',
  '2026 병 복지 길라잡이 67\n고용노동부 취업 안내 \n • 주관：전국 102개 고용(복지+)센터(www.workplus.go.kr)\n • 이용대상：전 국민, 전역 후 활용 가능\n • 이용절차\n - 고용(복지+)센터 방문 또는 고용24(www.work24.go.kr)에서 구직 신청\n - 구직자에게 일자리 정보 및 취업특강 등 취업지원 프로그램 제공\n - 국민취업지원제도* 등을 통해 취약계층 대상 통합적인 고용서비스\n (취업상담-직업훈련-취업알선) 제공\n \n* 소득, 재산 등 지원요건 해당 시 생계지원(구직촉진수당) \n < 고용(복지+)센터 구직자 취업지원 서비스 흐름도 > \n<고용24 구직신청>\n- 고용24에서 개인회원으\n로 가입하여 직접 구직\n신청\n- 또는 고용(복지+)센터\n에 방문하여 구직 신청\n서 제출\n<직업상담 및 취업알선>\n- 고용(복지+)센터: 적합한 진\n로선택을 위한 직업상담을 \n실시하고, 그 능력과 취업 \n희망조건에 적합한 일자리\n를 소개하거나 구직기술 향\n상 및 고용정보 제공을 위한 \n취업지원프로그램 등 운영 \n- 구직자는 고용24에서 일자\n리정보를 검색하여 직접 입\n사지원 가능\n<취업 및 결과 통보>\n- 구인, 구직자는 고용24\n으로 채용결과를 직접 \n입력하거나 고용(복지+)\n센터에 채용결과를 통보 \n- 미취업 시 고용(복지+)센\n터에 취업지원서비스 등\n을 다시 신청\n - 훈련비 지원을 위한 국민내일배움카드(직업능력개발계좌) 발급 \n \n* 고용24(www.work24.go.kr)에서 신청 가능(실업자는 먼저 구직 신청을 완료해야 가능)\n \n* 추천 : 국방부, 국가보훈부 / 운영 : 고용노동부\n • 문의처 \n - 고용노동부 고객상담센터 (국번 없이 1350) \n \n* 평일 오전 9시~ 오후 6시 상담(주말 및 공휴일 휴무)\n - 고용24(www.work24.go.kr) 홈페이지'],
 ['01\nPart\n자\n기\n개\n발\n \n및\n \n전\n직\n지\n원\n \n분\n야\n67 \n03\nPart\n2026 초급간부 길라잡이\n-③-Ⅵ\n국민내일배움카드(고용노동부) \n-③-Ⅶ\n기 타\n 개 요 \n \x07전 생애에 걸친 직무수행능력 습득·향상을 위해 국민 스스로 직업능력개발훈련을 \n실시할 수 있도록 훈련비 등 지원\n* 단, 관련 법령에 따라 공무원, 군인 등 일부 대상 제외\n* \x07군인의 경우, 국민 평생 직업능력 개발법 시행령 제6조 및 군인사법 시행령 제60조의2에 \n따라 단기복무 전역예정자의 경우 예외적으로 지원\n 주요내용\n •(신청자격) 신청일 기준 ① 5년 미만의 기간동안 현역으로 복무하고, \n ② 전역예정일까지의 기간이 6개월 이하인 장교·준사관 또는 부사관\n •(지원내용) 계좌발급일로부터 5년간 300만원 이내 훈련비 지원*\n* 훈련과정 직종별 취업률, 소득수준 등에 따라 훈련비 일정비율(0~55%) 자비 부담\n •(신청절차)\n신청인\n⇨\n각 군\n⇨\n관할 고용센터\n⇨\n훈련생·훈련기관\n• \x07신청서 작성 후 \n소속부대 담당자\n에게 제출\n•신청자격 확인 \n•\x07관할 고용센터에\n 추천 공문 발송\n•\x07신청인이 방문하여 \n발급절차 진행\n•\x07개인별 훈련과정 신청 \n및 실시\n* \x07(참고) 군 전직 및 취업 지원 업무에 관한 훈령 제11조의2 및 별지 제8호 서식(훈련과정) \n한국기술교육대학교(직업능력심사평가원) 등의 심사결과에 따라 지방관서의 장이 인정·\n통지하는 훈련과정\n* \x07국민내일배움카드 사업내용 및 훈련과정 등 구체적인 내용은 고용24 홈페이지 (www.work24.\ngo.kr)에서 확인\n 취업정보 제공 \n •국방일보 취업정보 게재 (매주 화요일) : (http://kookbang.dema.mil.kr)\n •온라인(인터넷)을 통한 정보확인\n - \x07국방전직교육원(www.moti.or.kr) \n - 고용부 워크넷(www.work.go.kr)\n - 중소벤처기업진흥공단(www.kosmes.or.kr)\n - 국가보훈부 제대군인지원센터(www.vnet.go.kr)\n - 나라일터(www.gojobs.go.kr) 등\n국방부 일자리정책과 취업지원정책 | 900-6635\n담당부서',
  '2026 병 복지 길라잡이 13\n나라사랑카드의 개인 병역정보(병역증, 전역증) 확인방법\n • 나라사랑카드 IC칩에 탑재된 개인 병역정보 현황\n구 분\n전자병역증\n전자전역증\n대 상\n현역 복무 중인 병사, 입대 예정인 장정\n예비역\n * 탑재된 개인 병역정보는 암호화되어 안전하며, 본인 외 열람 및 조회 불가\n * 전자병역증은 100% 탑재 중이나, 전자전역증은 소속부대별로 상이\n • 나라사랑카드 개인별 병역정보 확인방법\n - NFC기능이 있는 본인 명의의 스마트폰을 준비\n - “나라사랑포털” APP 검색 / 설치\n \n - “나라사랑포털”APP 로그인\n - 가운데 “퀵메뉴” → 병역/전역증 → 병역/전역증 조회 선택 \n - 나라사랑카드를 스마트폰에 태그하여 개인 병역정보 확인\n⇨',
  'Part 01 생활편의 분야\n12 2026 병 복지 길라잡이\n기타 서비스\n \n구 분\n혜 택\n하나은행\n• P.X. 최대 30% 캐시백\n• 대중교통(버스, 지하철) 20% 캐시백\n• T우주 유튜브프리미엄 6천원 캐시백\n• 쿠팡, 네이버쇼핑 20% 캐시백\n• 택시업종, 카카오T(택시) 20% 캐시백\n• 배달의민족, 쿠팡이츠, 요기요 20% 캐시백\nIBK기업은행\n• P.X. 최고 50% 할인\n• 편의점 20% + 10% 혜택\n• 네이버페이 10% 중복적립\n• 대중교통(버스, 지하철) 최대 20% 청구할인\n• PC방, 쇼핑, 배달 10% 할인 (쿠팡, 네이버+ 스토어 등)\n신한은행\n• P.X. 최대 30% 캐시백\n• 대중교통(버스, 지하철) 20% 캐시백\n• T우주 유튜브프리미엄 6천원 캐시백\n• 쿠팡, 네이버쇼핑 20% 캐시백\n• 택시업종, 카카오T(택시) 20% 캐시백\n• 배달의민족, 쿠팡이츠, 요기요 20% 캐시백\n * 전월 사용실적 및 통합 할인한도 등 은행별 적용 조건 및 할인율, 서비스가\n상이하므로 은행별 서비스 안내서 확인(나라사랑포털 www.narasarang.or.kr)\n군 복무 중 나라사랑카드 발급방법\n • 휴가 및 외출 시 발급받는 방법\n - 휴가, 외출 시 부대 또는 거주지 인근의 하나은행, IBK기업은행, 신한은행\n지점에 방문하여 가입신청서 작성(신분증 지참)\n - 본인 명의 휴대폰으로 하나은행, IBK기업은행, 신한은행 모바일 APP을\n이용하여 발급\n - 카드 수령 : 해당부대 또는 본인이 기입한 주소로 등기 배송(10일 소요)\n * 본인이 직접 수령해야 하므로 수령이 용이한 장소를 선택\n • 부대에서 발급받는 방법(훈련소, 신병교육대 등)\n - 소속 부대로 하나은행, IBK기업은행, 신한은행의 직원이 방문 시 현장에서\n가입신청서 작성(신분증 지참)\n - 카드 수령 : 해당(소속) 부대로 등기 배송(최대 7일 소요)',
  '2026 병 복지 길라잡이 15\n나라사랑포털 운영\n나라사랑포털 운영\n 병역판정검사부터 군 복무(사회복무요원, 대체복무 포함), 예비군 임무수행까지 \n나라사랑카드를 소지한 병역의무자에게 편의를 제공하고자 운영 중인 포털\n사이트\n • 가입 대상 \n - 병역판정검사 시 나라사랑카드를 발급한 병역의무자\n • 가입 절차\n - 자동가입 : 병역판정검사 시 나라사랑카드 발급자 \n - 별도가입: 나라사랑카드 미발급자 중 현역 병사(나라사랑고객센터 확인)\n • 모바일APP으로 이용 가능\n \n \n⇨\n • 주요 기능 \n \n구 분\n주요 기능\n입대 전\n- 병역판정검사 전 나라사랑카드 사전 신청 \n- 입영통지서 전자우편 수신\n- 병무청 여비계좌 조회 및 변경(등록) 기능\n복무 중\n- 장병내일준비적금 가입자격확인서 발급, 온라인 비대면 가입\n- 급여명세서 e-메일 수령(국군재정관리단 발송)\n- 각종 복지서비스 이용 안내\n전역 후\n- 전자전역증 발급 시 “전역 확인 증명서” 전자우편 수신\n- 전시동원 소집통지서 등의 전자우편 수신\n공 통\n- 나라사랑카드 주요서비스 안내\n- 나라사랑카드 전자병역증ㆍ전역증 탑재 및 조회 안내\n- 나라사랑 이메일 사용 가능(0000000@narasarang.or.kr)\n- 나라사랑카드 관련 공지사항 및 이벤트 안내\n * 나라사랑카드 계좌 잔액확인, 거래내용 확인 등 금융업무는 해당 금융사 홈페이지를 \n통해 확인 가능',
  '2026 병 복지 길라잡이 67\n고용노동부 취업 안내 \n • 주관：전국 102개 고용(복지+)센터(www.workplus.go.kr)\n • 이용대상：전 국민, 전역 후 활용 가능\n • 이용절차\n - 고용(복지+)센터 방문 또는 고용24(www.work24.go.kr)에서 구직 신청\n - 구직자에게 일자리 정보 및 취업특강 등 취업지원 프로그램 제공\n - 국민취업지원제도* 등을 통해 취약계층 대상 통합적인 고용서비스\n (취업상담-직업훈련-취업알선) 제공\n \n* 소득, 재산 등 지원요건 해당 시 생계지원(구직촉진수당) \n < 고용(복지+)센터 구직자 취업지원 서비스 흐름도 > \n<고용24 구직신청>\n- 고용24에서 개인회원으\n로 가입하여 직접 구직\n신청\n- 또는 고용(복지+)센터\n에 방문하여 구직 신청\n서 제출\n<직업상담 및 취업알선>\n- 고용(복지+)센터: 적합한 진\n로선택을 위한 직업상담을 \n실시하고, 그 능력과 취업 \n희망조건에 적합한 일자리\n를 소개하거나 구직기술 향\n상 및 고용정보 제공을 위한 \n취업지원프로그램 등 운영 \n- 구직자는 고용24에서 일자\n리정보를 검색하여 직접 입\n사지원 가능\n<취업 및 결과 통보>\n- 구인, 구직자는 고용24\n으로 채용결과를 직접 \n입력하거나 고용(복지+)\n센터에 채용결과를 통보 \n- 미취업 시 고용(복지+)센\n터에 취업지원서비스 등\n을 다시 신청\n - 훈련비 지원을 위한 국민내일배움카드(직업능력개발계좌) 발급 \n \n* 고용24(www.work24.go.kr)에서 신청 가능(실업자는 먼저 구직 신청을 완료해야 가능)\n \n* 추천 : 국방부, 국가보훈부 / 운영 : 고용노동부\n • 문의처 \n - 고용노동부 고객상담센터 (국번 없이 1350) \n \n* 평일 오전 9시~ 오후 6시 상담(주말 및 공휴일 휴무)\n - 고용24(www.work24.go.kr) 홈페이지'],
 ['이 표는 **각 군(육군·해군·공군·해병)의 장기복무(연장복무) 선발 안내**를 정리한 것으로, 장기복무 선발계획이 **홈페이지에 게시되는 시기**와 함께 선발 준비 시 확인해야 할 사항을 담고 있습니다. 컬럼은 문서 제목 아래에 각 군별 **장교/부사관 선발계획 탑재 시기**를 구분해 적고 있으며, 육군은 장교 전반기 전년도 12월·후반기 8월, 부사관 4월, 해군은 장교·부사관 전반기 1월, 부사관 후반기 6월, 공군은 장교 전반기 2월·부사관 전반기 1월, 해병은 장교 전반기 2월·후반기 9월, 부사관 전반기 3월·후반기 10월로 제시합니다. 또한 선발절차·추진일정·평가기준 등은 매년 최신화되며, 책임감 있는 임무수행과 대인관계, 관련 자격증 취득 같은 자기개발이 중요하다고 안내합니다. 마지막으로 장기복무 문의처와 각 군의 **선발 담당 부서/연',
  '10 \n2026 초급간부 길라잡이\n-①-Ⅰ\n장기복무 지원 및 선발과정\n 선발일정 : 신분별 연 1~2회 \n•육군 : 장교 전·후반기/부사관 전반기 •해군 : 전반기/부사관 전·후반기\n•공군 : 장교 전반기/부사관 전반기 •해병 : 장교 전·후반기/부사관 전·후반기\n* 각 군별 대상 및 기간 공문 확인 필요(인사참모)\n 지원대상\n구 분\n장 교\n부사관\n육 군\n(전반기)임관 5년차 이상 \n(후반기)임관 2∼3년차\n임관 3년차 ∼ 7년차\n해 군\n임관 3년차 ∼ 9년차\n임관 3년차 ∼ 7년차\n공 군\n임관 3년차 ∼ 9년차\n임관 4년차 ∼ 7년차\n해 병\n임관 2년차 ∼ 4년차\n임관 3년차 ∼ 5년차\n 선발비율\n구 분\n장 교\n부사관\n육 군\n2년차 60%, 3년차 20%,\n5년차∼7년차 20%\n3년차 40%, 4년차 50% \n5년차∼7년차 10%\n해 군\n3년차 70%, 4년차 30%,\n이후 결원발생 시\n3년차 70%, 4년차 30%,\n이후 결원발생 시\n공 군\n3년차 70%, 4년차 30%,\n이후 결원발생 시\n4년차 60% 5년차 40%,\n이후 결원발생 시\n해 병\n2년차 30%, 3년차 40%,\n4년차 30%, 이후 결원발생 시\n3년차 40%, 4년차 30%,\n5년차 30%\n* 선발비율은 군 인력운영 수준을 고려 각 군별 조정 가능\n 선발절차\n①선발계획 공지 → ②지원서접수/신원조사 → (육군, AI 면접) → \n③부대추천 심의 → ④면접평가 → ⑤선발심의 → ⑥합격자 발표\n-① 장기/연장복무제도\n각 군별 담당\n담당부서',
  '01\nPart\n인\n사\n제\n도\n \n근\n무\n \n분\n야\n11 \n/\n2026 초급간부 길라잡이\n01\nPart\n장기복무 선발 길라잡이\n 장기복무 선발 혜택 \n• 소령(상사) 진출 기회 부여 → 직업안정성 보장 \n * 계급별 연령 정년 : 50세(소령), 53세(상사) \n• 군사교육(전문학위 위탁교육, 영어반 교육 등) 선발 조건 부여 \n• 국외연수, 국방무관, UN PKO 등 해외 근무 조건 부여\n 당해 연도 각 군별 장기복무 선발계획을 확인, 준비 필요\n•평가요소 및 배점\n구 분\n계\n근무\n평정\n교육 \n성적\n상훈\n부대 \n평가\n부대\n추천\n면접\n평가\n체력 \n검정\n잠재 \n역량\n질적 \n평가\n육 \n군\n장 \n교\n2~3년100\n25\n5\n5\n10\n30\n10\n5\n-\n5\n5년차\n이상\n100\n40\n5\n5\n10\n25\n-\n5\n-\n-\n부\n사\n관\n3~4년100\n35\n5\n5\n10\n15\n10\n5\n5\n5\n5년차\n이상\n100\n50\n10\n0\n* 격오지 근무경력 가점 : 최대 1점 부여\n구 분\n계\n근무\n평정\n교육 \n성적\n상훈\n부대 \n평가\n체력 \n검정\n인성\n평가\n기술\n자격\n해상/\n전방\n잠재 \n역량\n위원회\n평가\n해\n군\n장 교\n100\n45\n10\n5\n15\n5\n-\n-\n-\n10\n10\n부사관100\n30\n15\n5\n20\n5\n5\n5\n10\n20\n5\n구 분\n계\n근무\n평정\n교육 \n성적\n상훈\n보직\n관리\n부대\n평가\n체력\n검정\n전문\n능력\n선발\n심사\n공 \n군\n장 교\n100\n25\n10\n3\n2\n20\n5\n5\n30\n부사관\n90\n20\n10\n5\n5\n15\n10\n5\n20\n구 분\n계\n근무\n평정\n교육 \n성적\n상훈\n부대 \n평가\n체력 \n검정\n잠재 \n역량\n위원회\n평가\n해\n병\n대\n장 교\n100\n70\n10\n3\n-\n3\n4\n10\n부사관\n100\n45\n10\n3\n10\n15\n7\n10\n•\x07각 군 장교 및 부사관 장기복무 심사 담당부서에서 심의 2∼3개월 전 \n홈페이지 게시 및 각 부대(인사/행정참모)로 공문 발송\nTip',
  '12 \n2026 초급간부 길라잡이\n장기복무 선발 길라잡이\n 장기복무 선발계획 각 군 홈페이지 탑재 시기\n•육군 : 장교 전반기 전년도 12월, 후반기 8월 / 부사관 4월\n•해군 : 장교·부사관 전반기 1월 / 부사관 후반기 6월\n•공군 : 장교 전반기 2월 / 부사관 전반기 1월\n•해병 : 장교 전반기 2월, 후반기 9월 / 부사관 전반기 3월, 후반기 10월\n* 공군은 선발결과만 홈페이지 게시, 계획은 공문으로 전파\n* 각 군별 선발절차 및 추진일정, 선발방법 및 평가기준 등 탑재되어,매년 최신화되는 \n 세부평가 요소를 확인해서 준비 필요\n 책임감 있는 임무수행과 부대에 기여하는 자세가 중요\n•본인 소관 업무를 책임감 있게 수행하고, \n•\x07특히, 부대원(상급자, 하급자, 동료)과 원만한 관계를 유지하면서, \n 해당 특기/분야에서 인정하는 자격증 등을 취득하는 자기개발 활동 필요\n 장기(연장) 복무 관련 문의사항 : 각 부대 인사참모 소관\n 장기(연장) 복무 선발 담당 현황\n•육군 : 인사사령부 인력획득계획과 장기복무선발담당(960-7161~3)\n•해군 : 해군본부 장교인사과 장교복무/특기관리담당(910-1216)\n 부사관/병인사과 부사관/병인사담당(910-1221)\n•공군 : 공군본부 장교인사과 장교경력관리담당(920-1438)\n 부사관/병인사과 부사관/병인사운영담당(910-1147)\n•해병 : 해병대사 인사운영과 장교인사담당(928-3121)\n 인사운영과 부사관/병인사담당(928-3122)\nTip',
  '01\nPart\n인\n사\n제\n도\n \n근\n무\n \n분\n야\n13 \n/\n2026 초급간부 길라잡이\n01\nPart\n복무연장 관련 알아두어야 할 사항\n \x07복무연장 지원기간은 임관일 기준으로 장교는 10년, 부사관은 \n7년을 넘지 않는 범위에서 복무연장 신청이 가능하며, 1회 신청시 \n4년 범위 내 연단위로 신청 가능(단, 공군은 1년 단위 지원) \n \x07당해 연도 선발계획을 확인하고 평가요소별 준비 필요\nTip\n 선발일정 : 연 1~2회 \n•육군 : 연 1∼2회(장교 전·후반기/부사관 4월) •해군 : 연 2회(전반기, 후반기)\n•공군 : 연 1회(장교 5월/부사관 4월) •해병 : 연 2회(전반기, 후반기)\n 지원대상\n구 분\n장 교\n부사관\n육 군\n임관 2년차 ∼ 9년차\n임관 3년차 ∼ 7년차\n해 군\n임관 2년차 ∼ 9년차\n임관 4년차 ∼ 6년차\n공 군\n임관 2년차 ∼ 9년차\n임관 4년차 ∼ 5년차\n해 병\n임관 2년차 ∼ 9년차\n임관 3년차 ∼ 7년차\n 선발비율\n•각 군별 중기인력 수준을 고려하여 병과별 적정 비율 산정\n 선발절차\n①선발계획 공지 → ②지원서접수 → ③부대추천 심사 → ④선발심의 → \n⑤합격자 발표\n-①-Ⅱ\n복무연장 지원 및 선발과정\n각 군별 담당\n담당부서'],
 ['01\nPart\n인\n사\n제\n도\n \n근\n무\n \n분\n야\n11 \n/\n2026 초급간부 길라잡이\n01\nPart\n장기복무 선발 길라잡이\n 장기복무 선발 혜택 \n• 소령(상사) 진출 기회 부여 → 직업안정성 보장 \n * 계급별 연령 정년 : 50세(소령), 53세(상사) \n• 군사교육(전문학위 위탁교육, 영어반 교육 등) 선발 조건 부여 \n• 국외연수, 국방무관, UN PKO 등 해외 근무 조건 부여\n 당해 연도 각 군별 장기복무 선발계획을 확인, 준비 필요\n•평가요소 및 배점\n구 분\n계\n근무\n평정\n교육 \n성적\n상훈\n부대 \n평가\n부대\n추천\n면접\n평가\n체력 \n검정\n잠재 \n역량\n질적 \n평가\n육 \n군\n장 \n교\n2~3년100\n25\n5\n5\n10\n30\n10\n5\n-\n5\n5년차\n이상\n100\n40\n5\n5\n10\n25\n-\n5\n-\n-\n부\n사\n관\n3~4년100\n35\n5\n5\n10\n15\n10\n5\n5\n5\n5년차\n이상\n100\n50\n10\n0\n* 격오지 근무경력 가점 : 최대 1점 부여\n구 분\n계\n근무\n평정\n교육 \n성적\n상훈\n부대 \n평가\n체력 \n검정\n인성\n평가\n기술\n자격\n해상/\n전방\n잠재 \n역량\n위원회\n평가\n해\n군\n장 교\n100\n45\n10\n5\n15\n5\n-\n-\n-\n10\n10\n부사관100\n30\n15\n5\n20\n5\n5\n5\n10\n20\n5\n구 분\n계\n근무\n평정\n교육 \n성적\n상훈\n보직\n관리\n부대\n평가\n체력\n검정\n전문\n능력\n선발\n심사\n공 \n군\n장 교\n100\n25\n10\n3\n2\n20\n5\n5\n30\n부사관\n90\n20\n10\n5\n5\n15\n10\n5\n20\n구 분\n계\n근무\n평정\n교육 \n성적\n상훈\n부대 \n평가\n체력 \n검정\n잠재 \n역량\n위원회\n평가\n해\n병\n대\n장 교\n100\n70\n10\n3\n-\n3\n4\n10\n부사관\n100\n45\n10\n3\n10\n15\n7\n10\n•\x07각 군 장교 및 부사관 장기복무 심사 담당부서에서 심의 2∼3개월 전 \n홈페이지 게시 및 각 부대(인사/행정참모)로 공문 발송\nTip',
  '12 \n2026 초급간부 길라잡이\n장기복무 선발 길라잡이\n 장기복무 선발계획 각 군 홈페이지 탑재 시기\n•육군 : 장교 전반기 전년도 12월, 후반기 8월 / 부사관 4월\n•해군 : 장교·부사관 전반기 1월 / 부사관 후반기 6월\n•공군 : 장교 전반기 2월 / 부사관 전반기 1월\n•해병 : 장교 전반기 2월, 후반기 9월 / 부사관 전반기 3월, 후반기 10월\n* 공군은 선발결과만 홈페이지 게시, 계획은 공문으로 전파\n* 각 군별 선발절차 및 추진일정, 선발방법 및 평가기준 등 탑재되어,매년 최신화되는 \n 세부평가 요소를 확인해서 준비 필요\n 책임감 있는 임무수행과 부대에 기여하는 자세가 중요\n•본인 소관 업무를 책임감 있게 수행하고, \n•\x07특히, 부대원(상급자, 하급자, 동료)과 원만한 관계를 유지하면서, \n 해당 특기/분야에서 인정하는 자격증 등을 취득하는 자기개발 활동 필요\n 장기(연장) 복무 관련 문의사항 : 각 부대 인사참모 소관\n 장기(연장) 복무 선발 담당 현황\n•육군 : 인사사령부 인력획득계획과 장기복무선발담당(960-7161~3)\n•해군 : 해군본부 장교인사과 장교복무/특기관리담당(910-1216)\n 부사관/병인사과 부사관/병인사담당(910-1221)\n•공군 : 공군본부 장교인사과 장교경력관리담당(920-1438)\n 부사관/병인사과 부사관/병인사운영담당(910-1147)\n•해병 : 해병대사 인사운영과 장교인사담당(928-3121)\n 인사운영과 부사관/병인사담당(928-3122)\nTip',
  '이 표는 **각 군(육군·해군·공군·해병)의 장기복무(연장복무) 선발 안내**를 정리한 것으로, 장기복무 선발계획이 **홈페이지에 게시되는 시기**와 함께 선발 준비 시 확인해야 할 사항을 담고 있습니다. 컬럼은 문서 제목 아래에 각 군별 **장교/부사관 선발계획 탑재 시기**를 구분해 적고 있으며, 육군은 장교 전반기 전년도 12월·후반기 8월, 부사관 4월, 해군은 장교·부사관 전반기 1월, 부사관 후반기 6월, 공군은 장교 전반기 2월·부사관 전반기 1월, 해병은 장교 전반기 2월·후반기 9월, 부사관 전반기 3월·후반기 10월로 제시합니다. 또한 선발절차·추진일정·평가기준 등은 매년 최신화되며, 책임감 있는 임무수행과 대인관계, 관련 자격증 취득 같은 자기개발이 중요하다고 안내합니다. 마지막으로 장기복무 문의처와 각 군의 **선발 담당 부서/연',
  '10 \n2026 초급간부 길라잡이\n-①-Ⅰ\n장기복무 지원 및 선발과정\n 선발일정 : 신분별 연 1~2회 \n•육군 : 장교 전·후반기/부사관 전반기 •해군 : 전반기/부사관 전·후반기\n•공군 : 장교 전반기/부사관 전반기 •해병 : 장교 전·후반기/부사관 전·후반기\n* 각 군별 대상 및 기간 공문 확인 필요(인사참모)\n 지원대상\n구 분\n장 교\n부사관\n육 군\n(전반기)임관 5년차 이상 \n(후반기)임관 2∼3년차\n임관 3년차 ∼ 7년차\n해 군\n임관 3년차 ∼ 9년차\n임관 3년차 ∼ 7년차\n공 군\n임관 3년차 ∼ 9년차\n임관 4년차 ∼ 7년차\n해 병\n임관 2년차 ∼ 4년차\n임관 3년차 ∼ 5년차\n 선발비율\n구 분\n장 교\n부사관\n육 군\n2년차 60%, 3년차 20%,\n5년차∼7년차 20%\n3년차 40%, 4년차 50% \n5년차∼7년차 10%\n해 군\n3년차 70%, 4년차 30%,\n이후 결원발생 시\n3년차 70%, 4년차 30%,\n이후 결원발생 시\n공 군\n3년차 70%, 4년차 30%,\n이후 결원발생 시\n4년차 60% 5년차 40%,\n이후 결원발생 시\n해 병\n2년차 30%, 3년차 40%,\n4년차 30%, 이후 결원발생 시\n3년차 40%, 4년차 30%,\n5년차 30%\n* 선발비율은 군 인력운영 수준을 고려 각 군별 조정 가능\n 선발절차\n①선발계획 공지 → ②지원서접수/신원조사 → (육군, AI 면접) → \n③부대추천 심의 → ④면접평가 → ⑤선발심의 → ⑥합격자 발표\n-① 장기/연장복무제도\n각 군별 담당\n담당부서',
  '14 \n2026 초급간부 길라잡이\n각 군별 담당\n담당부서\n 방위사업청 획득전문인력\n구 분\n내 용\n선발시기\n매년 6~9월 / 연 1회\n지원자격\n임관 7~10년 장교(각 군 대위 필수직위 이수자)\n선발인원\n24명(육군 40%, 해군·해병대 30%, 공군 30%)\n선발절차\n각 군 추천심의 → 방사청 선발심의\n※ 당해 연도 선발계획에 따라 변경될 수 있음\n 해외파병\n•\x07해외파병 현황\n부대파병(4개국 1,000여 명)\n개인파병(11개국 40여 명)\n레바논\n(동명)\n남수단\n(한빛)\n청해부대\n* 아덴만 해역\nUAE\n(아크)\nUN PKO \n다국적군\n300여 명\n300여 명\n300여 명\n150여 명\n20여 명\n20여 명 \n•\x07교대주기 : 부대파병 8개월, 개인파병 1년 단위\n•\x07지원자격 : 파병직위별 요구되는 자격과 어학능력 등 확인\n•\x07각 군별/신분별 소요에 따른 파병인원 선발공고 확인 후 지원\n 육군 항공장교\n구 분\n내 용\n선발시기\n매년 4월, 9월 / 연 2회\n지원자격\n기본병과 중위 1년차(해당병과 소대장 또는 참모보직 만료)\n선발인원\n약 70명\n선발절차\n서류심사 → 면접 → 선발심의\n※ 당해 연도 선발계획에 따라 변경될 수 있음\n 기타 교관/훈육요원, 법무, 수사관 등 \n •각 군별/신분별 소요에 따른 선발공고 확인 후 지원\n-② 대외부서 등 선발제도 및 절차'],
 ['이 표는 **취업알선 서비스의 구성 내용**을 정리한 것입니다. 주요 항목으로는 **채용정보 제공**, **직무/기업분석**, **그룹별 취업컨설팅**, **희망기업 알선**이 포함되어 있어, 구직자에게 맞춤형 취업 지원을 제공하는 내용을 나타냅니다. 컬럼의 제목인 **③ 취업알선**은 전체 프로그램의 세 번째 단계 또는 항목을 의미합니다.',
  '이 표는 **취업알선 서비스**의 구성 내용을 정리한 것으로, 구직자에게 **채용정보를 제공**하고 **직무 및 기업을 분석**하며, **희망하는 기업에 대한 알선**을 지원하는 항목을 담고 있습니다. 즉, 단순한 정보 안내를 넘어 구직자의 희망에 맞는 기업과 일자리를 연결해 주는 취업 지원 프로그램을 의미합니다. 주요 항목은 **채용정보 제공, 직무/기업분석, 희망기업 알선**의 3가지입니다.',
  '이 표는 **3차 상담** 단계에서 진행한 지원 내용을 요약한 것으로, 주로 **목표 추진 경과를 상담하고 취업처 및 취업정보를 제공해 매칭을 지원**하는 항목을 담고 있습니다. 즉, 상담의 핵심은 **현재 목표 달성 진행 상황 점검**과 **구체적인 취업 연계 정보 제공**입니다. 표의 항목 수치는 별도로 없고, 주요 내용은 **목표추진 경과 상담**, **취업처 제공**, **취업정보 제공**, **매칭 지원**으로 구성됩니다.',
  '이 표는 **취업성공 단계에서 제공되는 지원 항목**을 정리한 것으로, 컬럼은 구체적인 수치가 아니라 **취업 이후의 사후 지원 서비스**를 의미합니다. 주요 항목은 **직장적응지원, 경력개발지원, 취업성공사례관리, 취업기업관리**로 구성되어 있어, 구직자의 안정적인 근속과 경력 성장을 돕고 취업한 기업과의 관계를 관리하는 내용을 담고 있습니다.',
  '이 표는 **1:1 컨설팅 프로그램의 구성 내용**을 정리한 것입니다. 주요 항목은 **진로방향 및 목표 점검**, **역량·강점 분석**, **입사서류 클리닉**, **모의면접**의 4가지이며, 취업 준비 전반을 개인 맞춤형으로 지원하는 내용을 담고 있습니다. 즉, 컬럼은 **컨설팅에서 제공되는 세부 서비스 항목**을 의미합니다.'],
 ['이 표는 **취업알선 서비스**의 구성 내용을 정리한 것으로, 구직자에게 **채용정보를 제공**하고 **직무 및 기업을 분석**하며, **희망하는 기업에 대한 알선**을 지원하는 항목을 담고 있습니다. 즉, 단순한 정보 안내를 넘어 구직자의 희망에 맞는 기업과 일자리를 연결해 주는 취업 지원 프로그램을 의미합니다. 주요 항목은 **채용정보 제공, 직무/기업분석, 희망기업 알선**의 3가지입니다.',
  '이 표는 **취업알선 서비스의 구성 내용**을 정리한 것입니다. 주요 항목으로는 **채용정보 제공**, **직무/기업분석**, **그룹별 취업컨설팅**, **희망기업 알선**이 포함되어 있어, 구직자에게 맞춤형 취업 지원을 제공하는 내용을 나타냅니다. 컬럼의 제목인 **③ 취업알선**은 전체 프로그램의 세 번째 단계 또는 항목을 의미합니다.',
  '이 표는 **취업성공 단계에서 제공되는 지원 항목**을 정리한 것으로, 컬럼은 구체적인 수치가 아니라 **취업 이후의 사후 지원 서비스**를 의미합니다. 주요 항목은 **직장적응지원, 경력개발지원, 취업성공사례관리, 취업기업관리**로 구성되어 있어, 구직자의 안정적인 근속과 경력 성장을 돕고 취업한 기업과의 관계를 관리하는 내용을 담고 있습니다.',
  '이 표는 **회원 등록 시 진행하는 초기 절차와 안내 내용**을 정리한 것으로, **대상은 단기복무자**입니다. 주요 항목은 **초기상담**, **취업프로그램 안내**, **컨설팅 안내**이며, 회원 등록 단계에서 제공되는 기본 지원 서비스를 보여줍니다. 즉, 이 표는 단기복무자를 대상으로 한 등록 초기의 상담 및 취업 지원 안내 내용을 담고 있습니다.',
  '취업 및 창업 지원\n장병 경제교육\n국민연금 군 복무 크레딧\n국가보훈대상자 등록\n예비군훈련 안내\n상비예비군 제도\n예비역 병 ⇨ 부사관(하사) 임용\nPart 06\n사회적응 지원 분야'],
 ['01\nPart\n진\n료\n \n및\n \n재\n해\n보\n상\n \n분\n야\n75 \n04\nPart\n2026 초급간부 길라잡이\n •청구 및 지급절차\n ① 본인이 소속부대(의무조사 후 군병원에서 전역 시 군병원)에 신청\n ② \x07신청받은 부대의 장이 사실관계 조사 후 관련 서류를 첨부하여 \n재정단으로 청구 \n ③ \x07재정단에서 관련 서류 접수/확인 후 국방부(군인재해보상과) 제출\n ④ 군인재해보상심의회 심의 및 청구인에게 결과 통보\n ⑤ 심의 결과를 반영하여 재정단에서 지급\n •상이유족연금 : 상이연금 수급자가 사망한 때 유족에게 지급\n - 지급액 : 상이연금의 60% (’13.7월 이전 임용자는 70%)\n 사망보상금\n \x07•\x07군인이 공무 수행 중 사망한 경우, 그 유족(배우자, 자녀, 부모, 손자녀, 조부모) 중 \n「민법」에 따른 상속 우선 순위자에게 지급\n사망 구분\n보 상 기 준\n금 액(’25년 기준)\n전사\n공무원 전체 기준소득월액 평균액×60\n3억 4,260만원\n특수직무순직\n공무원 전체 기준소득월액 평균액×45\n2억 5,695만원\n일반순직\n공무원 전체 기준소득월액 평균액×24\n1억 3,704만원\n* ’25년 공무원 전체 기준소득월액 평균액 : 571만원 \n •청구 및 지급절차\n ① \x07각 군 전공사상심사위원회에서 순직여부 결정 후 유족에게 신청절차 \n안내\n ② \x07유족 신청 시 국군재정관리단에서 순직여부 확인 및 지급 결정 후 \n청구인에게 통보\n ③ \x07국군재정관리단에서 급여액 산정 및 사망보상금 지급\n •순직유족연금 : 복무 중 공무상 사망자의 유족에게 지급\n - \x07지급액 : 기준소득월액의 43%, 유족 1명당 5%씩, 최대 4명까지 20% 가산\n •순직유족연금일시금 : 순직유족연금에 갈음하여 일시 지급\n - 지급액 : 기준소득월액X복무년수[0.975+｛(복무년수-5)X0.0065｝]',

In [41]:
#
# eval_df에 컬럼으로 추가
#
eval_df['response'] = response_list
eval_df['retrieved_contexts'] = retrieved_context_list
eval_df

,user_input,reference_contexts,reference,persona_name,query_style,query_length,synthesizer_name,response,retrieved_contexts
0,국방일보 취업정보 어디서 볼수 있나요?,[01\nPart\n자\n기\n개\n발\n \n및\n \n전\n직\n지\n원\n \...,국방일보 취업정보는 매주 화요일 국방일보 홈페이지(http://kookbang.de...,Job Seeker in Career Transition,MISSPELLED,MEDIUM,single_hop_specific_query_synthesizer,국방일보 취업정보는 **국방일보 홈페이지**에서 볼 수 있습니다. \n경로는 다음...,[01\nPart\n자\n기\n개\n발\n \n및\n \n전\n직\n지\n원\n \...
1,국방일보에서 국민내일배움카드 관련 취업정보를 어떻게 확인할 수 있나요?,[01\nPart\n자\n기\n개\n발\n \n및\n \n전\n직\n지\n원\n \...,"국방일보에서는 매주 화요일 취업정보를 게재하며, 국민내일배움카드 관련 취업정보도 확...",Soon-to-be Discharged Service Member,WEB_SEARCH_LIKE,MEDIUM,single_hop_specific_query_synthesizer,"국방일보의 취업정보는 **매주 화요일 국방일보에 게재**되며, \n해당 정보는 *...",[01\nPart\n자\n기\n개\n발\n \n및\n \n전\n직\n지\n원\n \...
2,장교 선발계획이 언제 어디에 올라오는지 알 수 있나요? 그리고 장교로 장기복무를 준...,[이 표는 **각 군(육군·해군·공군·해병)의 장기복무(연장복무) 선발 안내**를 ...,장교 선발계획은 각 군별로 홈페이지에 게시되는 시기가 다릅니다. 육군은 장교 전반기...,Soon-to-be Discharged Service Member,MISSPELLED,LONG,single_hop_specific_query_synthesizer,"네, Context에 따르면 장교 선발계획은 **각 군 홈페이지**에 올라오며, 탑...",[이 표는 **각 군(육군·해군·공군·해병)의 장기복무(연장복무) 선발 안내**를 ...
3,부사관 장기복무 선발계획은 언제 확인할 수 있습니까?,[이 표는 **각 군(육군·해군·공군·해병)의 장기복무(연장복무) 선발 안내**를 ...,"부사관 장기복무 선발계획은 육군 4월, 해군 전반기 1월과 후반기 6월, 공군 전반...",Military Career Progression Advisor,PERFECT_GRAMMAR,SHORT,single_hop_specific_query_synthesizer,부사관 장기복무 선발계획은 각 군별로 홈페이지에 게시되는 시기가 다릅니다.\n\n-...,[01\nPart\n인\n사\n제\n도\n \n근\n무\n \n분\n야\n11 \n...
4,③ 취업알선 단계에서 제공되는 맞춤형 취업 지원 서비스에는 어떤 내용이 포함되어 있...,[이 표는 **취업알선 서비스의 구성 내용**을 정리한 것입니다. 주요 항목으로는 ...,"③ 취업알선 단계에서 제공되는 맞춤형 취업 지원 서비스에는 채용정보 제공, 직무 및...",Job Seeker in Career Transition,PERFECT_GRAMMAR,LONG,single_hop_specific_query_synthesizer,"③ 취업알선 단계에서 제공되는 맞춤형 취업 지원 서비스에는 **채용정보 제공, 직무...",[이 표는 **취업알선 서비스의 구성 내용**을 정리한 것입니다. 주요 항목으로는 ...
5,취업알선 서비스에는 어떤 지원이 포함되어 있나요?,[이 표는 **취업알선 서비스의 구성 내용**을 정리한 것입니다. 주요 항목으로는 ...,"취업알선 서비스에는 채용정보 제공, 직무/기업분석, 그룹별 취업컨설팅, 희망기업 알...",Job Seeker in Career Transition,WEB_SEARCH_LIKE,SHORT,single_hop_specific_query_synthesizer,"취업알선 서비스에는 **채용정보 제공, 직무/기업분석, 그룹별 취업컨설팅, 희망기업...","[이 표는 **취업알선 서비스**의 구성 내용을 정리한 것으로, 구직자에게 **채용..."
6,"국군재정관리단장 뭐 하는 사람인지 궁금해요, 사망보상금 받을 때 국군재정관리단장 역...",[Part 05 재해보상 분야\n58 2026 병 복지 길라잡이\n 재해보상금의 종...,사망보상금 받을 때 국군재정관리단장은 중요한 역할을 해요. 순직여부가 각 군 전공사...,Job Seeker in Career Transition,POOR_GRAMMAR,LONG,single_hop_specific_query_synthesizer,"제공된 context에 따르면, **사망보상금 청구·지급 절차에서 국군재정관리단장*...",[01\nPart\n진\n료\n \n및\n \n재\n해\n보\n상\n \n분\n야\...
7,각 군 전공사상심사위원회는 어떤 역할을 하나요?,[Part 05 재해보상 분야\n58 2026 병 복지 길라잡이\n 재해보상금의 종...,각 군 전공사상심사위원회에서는 순직여부를 결정합니다.,Military Career Progression Advisor,PERFECT_GRAMMAR,SHORT,single_hop_specific_query_synthesizer,정보가 부족해 답을 할 수없습니다.,[이 표는 **육군 간부 선발 또는 평가 시 항목별 배점 기준**을 정리한 것으로 ...

In [42]:
# eval_df를 ragas의 평가데이터셋 타입으로 변환
from ragas import EvaluationDataset
eval_dataset = EvaluationDataset.from_pandas(
    eval_df[["user_input", "retrieved_contexts", "response", "reference"]]
)
eval_dataset

EvaluationDataset(features=['user_input', 'retrieved_contexts', 'response', 'reference'], len=8)

In [43]:
#
# 평가
#
from ragas.metrics import (
    LLMContextRecall,
    LLMContextPrecisionWithReference,
    Faithfulness,
    AnswerRelevancy,
)
from ragas import evaluate

C:\Users\Playdata\AppData\Local\Temp\ipykernel_37040\3378832119.py:4: DeprecationWarning: Importing LLMContextRecall from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import LLMContextRecall
  from ragas.metrics import (
C:\Users\Playdata\AppData\Local\Temp\ipykernel_37040\3378832119.py:4: DeprecationWarning: Importing LLMContextPrecisionWithReference from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import LLMContextPrecisionWithReference
  from ragas.metrics import (
C:\Users\Playdata\AppData\Local\Temp\ipykernel_37040\3378832119.py:4: DeprecationWarning: Importing Faithfulness from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import Faithfulness
  from ragas.metrics import (
C:\Users\Playdata\AppData\Local\Temp\ipykernel_37040\3378832119.py:4: DeprecationWarning: Importing AnswerRelevancy from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import AnswerRelevancy
  from ragas.metrics import (

In [44]:
# 평가할 때 사용할 LLM embedding 모델
eval_llm = LangchainLLMWrapper(ChatOpenAI(model="gpt-4.1"))
eval_embeddings = LangchainEmbeddingsWrapper(OpenAIEmbeddings(model="text-embedding-3-large"))

metrics = [
    LLMContextRecall(llm=eval_llm),
    LLMContextPrecisionWithReference(llm=eval_llm),
    Faithfulness(llm=eval_llm),
    AnswerRelevancy(llm=eval_llm, embeddings=eval_embeddings)

]
eval_result = evaluate(dataset=eval_dataset, metrics=metrics)

C:\Users\Playdata\AppData\Local\Temp\ipykernel_37040\384477035.py:2: DeprecationWarning: LangchainLLMWrapper is deprecated and will be removed in a future version. Use llm_factory instead: from openai import OpenAI; from ragas.llms import llm_factory; llm = llm_factory('gpt-4o-mini', client=OpenAI(api_key='...'))
  eval_llm = LangchainLLMWrapper(ChatOpenAI(model="gpt-4.1"))
C:\Users\Playdata\AppData\Local\Temp\ipykernel_37040\384477035.py:3: DeprecationWarning: LangchainEmbeddingsWrapper is deprecated and will be removed in a future version. Use the modern embedding providers instead: embedding_factory('openai', model='text-embedding-3-small', client=openai_client) or from ragas.embeddings import OpenAIEmbeddings, GoogleEmbeddings, HuggingFaceEmbeddings
  eval_embeddings = LangchainEmbeddingsWrapper(OpenAIEmbeddings(model="text-embedding-3-large"))
Evaluating:   6%|▋         | 2/32 [00:06<01:35,  3.17s/it]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating:  28%|██▊       | 9/32 [00:07<00:15,  1.45it/s]LLM returned 1 generations instead of requested 3. Proceeding with 1 generations.
Evaluating:  94%|█████████▍| 30/32 [02:56<00:24, 12.30s/it]Exception raised in Job[14]: TimeoutError()
Evaluating: 100%|██████████| 32/32 [03:08<00:00,  5.88s/it]

In [45]:
eval_result

{'context_recall': 0.8750, 'llm_context_precision_with_reference': 0.8299, 'faithfulness': 0.8393, 'answer_relevancy': 0.4647}

In [46]:
result_df = eval_result.to_pandas()
result_df

,user_input,retrieved_contexts,response,reference,context_recall,llm_context_precision_with_reference,faithfulness,answer_relevancy
0,국방일보 취업정보 어디서 볼수 있나요?,[01\nPart\n자\n기\n개\n발\n \n및\n \n전\n직\n지\n원\n \...,국방일보 취업정보는 **국방일보 홈페이지**에서 볼 수 있습니다. \n경로는 다음...,국방일보 취업정보는 매주 화요일 국방일보 홈페이지(http://kookbang.de...,1.0,1.000000,1.0000,0.582092
1,국방일보에서 국민내일배움카드 관련 취업정보를 어떻게 확인할 수 있나요?,[01\nPart\n자\n기\n개\n발\n \n및\n \n전\n직\n지\n원\n \...,"국방일보의 취업정보는 **매주 화요일 국방일보에 게재**되며, \n해당 정보는 *...","국방일보에서는 매주 화요일 취업정보를 게재하며, 국민내일배움카드 관련 취업정보도 확...",1.0,1.000000,1.0000,0.677288
2,장교 선발계획이 언제 어디에 올라오는지 알 수 있나요? 그리고 장교로 장기복무를 준...,[이 표는 **각 군(육군·해군·공군·해병)의 장기복무(연장복무) 선발 안내**를 ...,"네, Context에 따르면 장교 선발계획은 **각 군 홈페이지**에 올라오며, 탑...",장교 선발계획은 각 군별로 홈페이지에 게시되는 시기가 다릅니다. 육군은 장교 전반기...,1.0,1.000000,0.9375,0.000000
3,부사관 장기복무 선발계획은 언제 확인할 수 있습니까?,[01\nPart\n인\n사\n제\n도\n \n근\n무\n \n분\n야\n11 \n...,부사관 장기복무 선발계획은 각 군별로 홈페이지에 게시되는 시기가 다릅니다.\n\n-...,"부사관 장기복무 선발계획은 육군 4월, 해군 전반기 1월과 후반기 6월, 공군 전반...",1.0,0.638889,NaN,0.752006
4,③ 취업알선 단계에서 제공되는 맞춤형 취업 지원 서비스에는 어떤 내용이 포함되어 있...,[이 표는 **취업알선 서비스의 구성 내용**을 정리한 것입니다. 주요 항목으로는 ...,"③ 취업알선 단계에서 제공되는 맞춤형 취업 지원 서비스에는 **채용정보 제공, 직무...","③ 취업알선 단계에서 제공되는 맞춤형 취업 지원 서비스에는 채용정보 제공, 직무 및...",1.0,1.000000,1.0000,0.800423
5,취업알선 서비스에는 어떤 지원이 포함되어 있나요?,"[이 표는 **취업알선 서비스**의 구성 내용을 정리한 것으로, 구직자에게 **채용...","취업알선 서비스에는 **채용정보 제공, 직무/기업분석, 그룹별 취업컨설팅, 희망기업...","취업알선 서비스에는 채용정보 제공, 직무/기업분석, 그룹별 취업컨설팅, 희망기업 알...",1.0,1.000000,1.0000,0.905505
6,"국군재정관리단장 뭐 하는 사람인지 궁금해요, 사망보상금 받을 때 국군재정관리단장 역...",[01\nPart\n진\n료\n \n및\n \n재\n해\n보\n상\n \n분\n야\...,"제공된 context에 따르면, **사망보상금 청구·지급 절차에서 국군재정관리단장*...",사망보상금 받을 때 국군재정관리단장은 중요한 역할을 해요. 순직여부가 각 군 전공사...,1.0,1.000000,0.9375,0.000000
7,각 군 전공사상심사위원회는 어떤 역할을 하나요?,[이 표는 **육군 간부 선발 또는 평가 시 항목별 배점 기준**을 정리한 것으로 ...,정보가 부족해 답을 할 수없습니다.,각 군 전공사상심사위원회에서는 순직여부를 결정합니다.,0.0,0.000000,0.0000,0.000000